// GENERATED by scripts/build.mjs from services/identity-svc/api/index.ts — do not edit directly.

// packages/server-core/src/http.ts
function allowedOrigins(env = process.env) {
  return (env.ALLOWED_ORIGINS ?? "").split(",").map((o) => o.trim()).filter((o) => o.length > 0);
}
function corsOriginFor(requestOrigin, env = process.env) {
  const allow = allowedOrigins(env);
  if (allow.length === 0) return { origin: "*", vary: false };
  if (requestOrigin && allow.includes(requestOrigin)) {
    return { origin: requestOrigin, vary: true };
  }
  return { origin: allow[0], vary: true };
}
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS", requestOrigin) {
  const { origin, vary } = corsOriginFor(requestOrigin);
  return {
    ...vary ? { Vary: "Origin" } : {},
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
async function readJson(req) {
  const raw = await readBody(req);
  return JSON.parse(raw);
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}
var HttpError = class extends Error {
  // Longhand rather than constructor parameter properties: node --test
  // strips types instead of compiling them, and parameter properties are the
  // one TS-only construct it cannot strip. Since every server module reaches
  // this file, that single construct made all of server-core un-testable
  // under the project's `node --test file.ts` convention.
  status;
  code;
  /**
   * Structured context spread into the error body alongside `error` and
   * `message`. For refusals a screen has to act on rather than merely print —
   * the routine editor naming the class that already owns an hour, say — a
   * sentence is what the user reads and this is what the UI renders. Optional
   * everywhere; an endpoint that has nothing to add omits it.
   */
  detail;
  constructor(status, message2, code, detail) {
    super(message2);
    this.status = status;
    this.code = code;
    this.detail = detail;
  }
};
var TenantBlocked = class extends HttpError {
  access;
  /**
   * The same sentence as `message`, under the name the rest of the product
   * uses for a Bangla string meant for a person. `message` is what a log
   * shows; this is what a screen shows, and keeping both makes it obvious at
   * a call site which one is being read.
   */
  reasonBn;
  constructor(access) {
    super(
      403,
      access.reasonBn ?? "\u098F\u0987 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u09C7\u09B0 \u0985\u09CD\u09AF\u09BE\u0995\u09BE\u0989\u09A8\u09CD\u099F\u09C7 \u098F\u0996\u09A8 \u098F\u0987 \u0995\u09BE\u099C\u099F\u09BF \u0995\u09B0\u09BE \u09AF\u09BE\u099A\u09CD\u099B\u09C7 \u09A8\u09BE\u0964",
      "tenant_blocked",
      {
        access: access.access,
        opsState: access.opsState,
        billingState: access.billingState,
        until: access.until,
        // B-84. Present only when a service was named. `not_in_plan` means
        // buy it; `disabled` and `maintenance` mean wait or ring us. Those
        // are different errands for the office and the screen must be able
        // to send them on the right one.
        ...access.serviceState ? { serviceState: access.serviceState } : {}
      }
    );
    this.access = access;
    this.reasonBn = this.message;
  }
};

// packages/server-core/src/db.ts
import pg from "pg";
pg.types.setTypeParser(1082, (v) => v);
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    let readOnlyFor;
    let released = false;
    try {
      await client.query("BEGIN");
      readOnlyFor = (await setup(client))?.blocked;
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      if (readOnlyFor && err?.code === "25006") {
        try {
          await client.query("ROLLBACK");
        } catch {
        }
        client.release();
        released = true;
        throw new TenantBlocked(readOnlyFor);
      }
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      if (!released) client.release();
    }
  }
  return {
    pool,
    async tenantAccess(tenantId) {
      return readAccess(pool, tenantId);
    },
    withTenant(ctx, fn, opts2) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        let blocked;
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
        if (opts2?.skipGate) return;
        const access = await readAccess(c, ctx.tenantId, ctx.role, ctx.service);
        if (access.access === "none") {
          if (ctx.service) {
            const { rows } = await c.query(
              "SELECT app.tenant_service_state($1, $2) AS state",
              [ctx.tenantId, ctx.service]
            );
            const state = rows[0]?.state;
            if (state) throw new TenantBlocked({ ...access, serviceState: state });
          }
          throw new TenantBlocked(access);
        }
        if (access.access === "read_only") {
          if (opts2?.sessionWrite) return { blocked: void 0 };
          await c.query("SET LOCAL transaction_read_only = on");
          blocked = access;
          if (opts2?.write) throw new TenantBlocked(access);
        }
        return { blocked };
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function readAccess(q, tenantId, role, service) {
  try {
    const { rows } = role && service ? await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1, $2, $3)`,
      [tenantId, role, service]
    ) : role ? await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1, $2)`,
      [tenantId, role]
    ) : await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1)`,
      [tenantId]
    );
    const r = rows[0];
    if (!r?.access) {
      return {
        access: "none",
        opsState: "unknown",
        billingState: "unknown",
        reasonBn: "\u098F\u0987 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u099F\u09BF \u0996\u09C1\u0981\u099C\u09C7 \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964",
        until: null
      };
    }
    return {
      access: r.access,
      opsState: r.ops_state ?? "unknown",
      billingState: r.billing_state ?? "unknown",
      reasonBn: r.reason_bn ?? null,
      until: r.until ? String(r.until).slice(0, 10) : null
    };
  } catch {
    return {
      access: "none",
      opsState: "unknown",
      billingState: "unknown",
      reasonBn: "\u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u09C7\u09B0 \u0985\u09AC\u09B8\u09CD\u09A5\u09BE \u09AF\u09BE\u099A\u09BE\u0987 \u0995\u09B0\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964 \u098F\u0995\u099F\u09C1 \u09AA\u09B0\u09C7 \u0986\u09AC\u09BE\u09B0 \u099A\u09C7\u09B7\u09CD\u099F\u09BE \u0995\u09B0\u09C1\u09A8\u0964",
      until: null
    };
  }
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
async function enforceIdentityRateLimit(res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, null, identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// packages/server-core/src/crypto.ts
import { randomBytes, randomInt, createHash, timingSafeEqual } from "node:crypto";
function randomOpaqueToken(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}
function randomOtpCode(digits = 6) {
  const max = 10 ** digits;
  return String(randomInt(0, max)).padStart(digits, "0");
}
function sha256Buf(input) {
  return createHash("sha256").update(input, "utf8").digest();
}
function constantTimeEqualHex(a, b) {
  const bufA = Buffer.from(a, "hex");
  const bufB = Buffer.from(b, "hex");
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
}

// packages/server-core/src/go-live.ts
function enabled(name, env = process.env) {
  return (env[name] ?? "").trim().toLowerCase() === "true";
}
function otpSendingEnabled(env = process.env) {
  return enabled("OTP_SENDING_ENABLED", env);
}

// packages/server-core/src/service-auth.ts
import { createHash as createHash2, timingSafeEqual as timingSafeEqual2 } from "node:crypto";
function keyFingerprint(key) {
  return createHash2("sha256").update(key, "utf8").digest("hex").slice(0, 8);
}
function sameSecret(a, b) {
  if (!a || !b) return false;
  const ha = createHash2("sha256").update(a, "utf8").digest();
  const hb = createHash2("sha256").update(b, "utf8").digest();
  return timingSafeEqual2(ha, hb);
}
function matchServiceKey(token, env = process.env, opts = {}) {
  if (!token) return null;
  if (env.SERVICE_API_KEY && sameSecret(token, env.SERVICE_API_KEY)) return "current";
  if (env.SERVICE_API_KEY_NEXT && sameSecret(token, env.SERVICE_API_KEY_NEXT)) return "next";
  if (opts.allowCron && env.CRON_SECRET && sameSecret(token, env.CRON_SECRET)) return "cron";
  return null;
}
function looksLikeBrowser(req) {
  for (const name of ["origin", "cookie", "sec-fetch-site"]) {
    const v = req.headers[name];
    if (typeof v === "string" ? v.length > 0 : Array.isArray(v) && v.length > 0) return name;
  }
  return null;
}
function tenantSwitchAllowed(env = process.env) {
  const flag = (env.SERVICE_KEY_TENANT_SWITCH ?? "").trim().toLowerCase();
  if (flag === "on" || flag === "true" || flag === "1") return true;
  if (flag === "off" || flag === "false" || flag === "0") return false;
  return env.NODE_ENV !== "production";
}
function logServiceKeyEvent(fields) {
  console.warn(JSON.stringify({ at: "service-auth", ...fields }));
}

// services/identity-svc/api/otp-request.ts
var PHONE_RE = /^\+8801[3-9][0-9]{8}$/;
var PURPOSES = /* @__PURE__ */ new Set(["login", "enrol_device", "reset_password", "verify_phone"]);
var MIN_RESEND_INTERVAL_SECONDS = 45;
var OTP_TTL_MINUTES = 5;
var OTP_TTL_MINUTES_BN = "\u09EB";
async function handler(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  if (!otpSendingEnabled()) {
    json(res, 503, { error: "otp_disabled", message: "OTP login is temporarily unavailable" }, cors);
    return;
  }
  try {
    const body = await readJson(req);
    const tenantId = body.tenantId ?? "";
    const phone = body.phone ?? "";
    const purpose = body.purpose ?? "login";
    if (!tenantId) throw new HttpError(400, "tenantId is required", "tenant_required");
    if (!PHONE_RE.test(phone)) throw new HttpError(400, "phone must be a valid +8801XXXXXXXXX number", "invalid_phone");
    if (!PURPOSES.has(purpose)) throw new HttpError(400, `purpose must be one of ${[...PURPOSES].join(", ")}`, "invalid_purpose");
    if (!await enforceIdentityRateLimit(res, cors, "otp_request", `${tenantId}:${phone}`)) return;
    const db = await sharedDb();
    const result = await db.withTenant({ tenantId, userId: "", role: "system_ingest" }, async (client) => {
      const recent = await client.query(
        `SELECT created_at FROM otp_challenges
          WHERE tenant_id = $1 AND phone_e164 = $2 AND purpose = $3
            AND consumed_at IS NULL AND expires_at > now()
          ORDER BY created_at DESC LIMIT 1`,
        [tenantId, phone, purpose]
      );
      if (recent.rows[0]) {
        const ageSeconds = (Date.now() - new Date(recent.rows[0].created_at).getTime()) / 1e3;
        if (ageSeconds < MIN_RESEND_INTERVAL_SECONDS) {
          throw new HttpError(429, "an OTP was already sent recently, please wait before retrying", "too_soon");
        }
      }
      const code = randomOtpCode(6);
      const codeHash2 = sha256Buf(code);
      const inserted = await client.query(
        `INSERT INTO otp_challenges (tenant_id, phone_e164, code_hash, purpose, expires_at)
         VALUES ($1, $2, $3, $4, now() + ($5 || ' minutes')::interval)
         RETURNING id, expires_at`,
        [tenantId, phone, codeHash2, purpose, OTP_TTL_MINUTES]
      );
      const org = await client.query(
        `SELECT name_bn FROM tenants WHERE id = $1`,
        [tenantId]
      );
      const orgName = org.rows[0]?.name_bn ?? "\u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC";
      const smsBody = `\u0986\u09AA\u09A8\u09BE\u09B0 \u09B2\u0997\u0987\u09A8 \u0995\u09CB\u09A1 ${code}\u0964 ${OTP_TTL_MINUTES_BN} \u09AE\u09BF\u09A8\u09BF\u099F\u09C7\u09B0 \u09AE\u09A7\u09CD\u09AF\u09C7 \u09AC\u09CD\u09AF\u09AC\u09B9\u09BE\u09B0 \u0995\u09B0\u09C1\u09A8\u0964 \u0995\u09BE\u0989\u0995\u09C7 \u099C\u09BE\u09A8\u09BE\u09AC\u09C7\u09A8 \u09A8\u09BE\u0964 \u2014 ${orgName}`;
      await client.query(
        `INSERT INTO sms_outbox
           (tenant_id, msisdn, template_code, locale, body, encoding, segments,
            priority, dedupe_key, context)
         VALUES ($1, $2, 'auth.otp.v1', 'bn', $3, 'unicode', $4, 1, $5, $6)`,
        [
          tenantId,
          phone,
          smsBody,
          // Bangla forces UCS-2: 70 characters to a segment, not 160.
          Math.max(1, Math.ceil(smsBody.length / 70)),
          // Keyed on the CHALLENGE, not on the phone and the day. A person
          // who did not receive the first code asks for another one, and the
          // daily dedupe index would have swallowed every retry after the
          // first — locking them out for the rest of the day.
          `otp:${inserted.rows[0].id}`,
          // The code itself is never put in `context`: that column is read
          // by the dispatcher's logs and by support.
          JSON.stringify({ purpose, challengeId: inserted.rows[0].id })
        ]
      );
      const debugKey = header(req, "x-debug-otp");
      const debugLabel = matchServiceKey(debugKey, process.env);
      const isDebugAuthorized = debugLabel !== null && tenantSwitchAllowed(process.env) && looksLikeBrowser(req) === null;
      if (debugLabel !== null) {
        logServiceKeyEvent({
          event: isDebugAuthorized ? "otp_debug_echo" : "otp_debug_echo_refused",
          endpoint: "auth/otp/request",
          fingerprint: keyFingerprint(debugKey),
          keyLabel: debugLabel
        });
      }
      return {
        challengeId: inserted.rows[0].id,
        expiresAt: inserted.rows[0].expires_at,
        ...isDebugAuthorized ? { debugCode: code } : {}
      };
    });
    json(res, 200, { ok: true, ...result }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[otp-request] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
import { Buffer as Buffer2 } from "node:buffer";

// node_modules/jose/dist/node/esm/lib/buffer_utils.js
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var MAX_INT32 = 2 ** 32;
function concat(...buffers) {
  const size = buffers.reduce((acc, { length }) => acc + length, 0);
  const buf = new Uint8Array(size);
  let i = 0;
  for (const buffer of buffers) {
    buf.set(buffer, i);
    i += buffer.length;
  }
  return buf;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
function normalize(input) {
  let encoded = input;
  if (encoded instanceof Uint8Array) {
    encoded = decoder.decode(encoded);
  }
  return encoded;
}
var encode = (input) => Buffer2.from(input).toString("base64url");
var decode = (input) => new Uint8Array(Buffer2.from(normalize(input), "base64url"));

// node_modules/jose/dist/node/esm/util/errors.js
var JOSEError = class extends Error {
  static code = "ERR_JOSE_GENERIC";
  code = "ERR_JOSE_GENERIC";
  constructor(message2, options) {
    super(message2, options);
    this.name = this.constructor.name;
    Error.captureStackTrace?.(this, this.constructor);
  }
};
var JWTClaimValidationFailed = class extends JOSEError {
  static code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JWTExpired = class extends JOSEError {
  static code = "ERR_JWT_EXPIRED";
  code = "ERR_JWT_EXPIRED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JOSEAlgNotAllowed = class extends JOSEError {
  static code = "ERR_JOSE_ALG_NOT_ALLOWED";
  code = "ERR_JOSE_ALG_NOT_ALLOWED";
};
var JOSENotSupported = class extends JOSEError {
  static code = "ERR_JOSE_NOT_SUPPORTED";
  code = "ERR_JOSE_NOT_SUPPORTED";
};
var JWSInvalid = class extends JOSEError {
  static code = "ERR_JWS_INVALID";
  code = "ERR_JWS_INVALID";
};
var JWTInvalid = class extends JOSEError {
  static code = "ERR_JWT_INVALID";
  code = "ERR_JWT_INVALID";
};
var JWSSignatureVerificationFailed = class extends JOSEError {
  static code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  constructor(message2 = "signature verification failed", options) {
    super(message2, options);
  }
};

// node_modules/jose/dist/node/esm/runtime/is_key_object.js
import * as util from "node:util";
var is_key_object_default = (obj) => util.types.isKeyObject(obj);

// node_modules/jose/dist/node/esm/runtime/webcrypto.js
import * as crypto from "node:crypto";
import * as util2 from "node:util";
var webcrypto2 = crypto.webcrypto;
var webcrypto_default = webcrypto2;
var isCryptoKey = (key) => util2.types.isCryptoKey(key);

// node_modules/jose/dist/node/esm/lib/crypto_key.js
function unusable(name, prop = "algorithm.name") {
  return new TypeError(`CryptoKey does not support this operation, its ${prop} must be ${name}`);
}
function isAlgorithm(algorithm, name) {
  return algorithm.name === name;
}
function getHashLength(hash) {
  return parseInt(hash.name.slice(4), 10);
}
function getNamedCurve(alg) {
  switch (alg) {
    case "ES256":
      return "P-256";
    case "ES384":
      return "P-384";
    case "ES512":
      return "P-521";
    default:
      throw new Error("unreachable");
  }
}
function checkUsage(key, usages) {
  if (usages.length && !usages.some((expected) => key.usages.includes(expected))) {
    let msg = "CryptoKey does not support this operation, its usages must include ";
    if (usages.length > 2) {
      const last = usages.pop();
      msg += `one of ${usages.join(", ")}, or ${last}.`;
    } else if (usages.length === 2) {
      msg += `one of ${usages[0]} or ${usages[1]}.`;
    } else {
      msg += `${usages[0]}.`;
    }
    throw new TypeError(msg);
  }
}
function checkSigCryptoKey(key, alg, ...usages) {
  switch (alg) {
    case "HS256":
    case "HS384":
    case "HS512": {
      if (!isAlgorithm(key.algorithm, "HMAC"))
        throw unusable("HMAC");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "RS256":
    case "RS384":
    case "RS512": {
      if (!isAlgorithm(key.algorithm, "RSASSA-PKCS1-v1_5"))
        throw unusable("RSASSA-PKCS1-v1_5");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "PS256":
    case "PS384":
    case "PS512": {
      if (!isAlgorithm(key.algorithm, "RSA-PSS"))
        throw unusable("RSA-PSS");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "EdDSA": {
      if (key.algorithm.name !== "Ed25519" && key.algorithm.name !== "Ed448") {
        throw unusable("Ed25519 or Ed448");
      }
      break;
    }
    case "Ed25519": {
      if (!isAlgorithm(key.algorithm, "Ed25519"))
        throw unusable("Ed25519");
      break;
    }
    case "ES256":
    case "ES384":
    case "ES512": {
      if (!isAlgorithm(key.algorithm, "ECDSA"))
        throw unusable("ECDSA");
      const expected = getNamedCurve(alg);
      const actual = key.algorithm.namedCurve;
      if (actual !== expected)
        throw unusable(expected, "algorithm.namedCurve");
      break;
    }
    default:
      throw new TypeError("CryptoKey does not support this operation");
  }
  checkUsage(key, usages);
}

// node_modules/jose/dist/node/esm/lib/invalid_key_input.js
function message(msg, actual, ...types4) {
  types4 = types4.filter(Boolean);
  if (types4.length > 2) {
    const last = types4.pop();
    msg += `one of type ${types4.join(", ")}, or ${last}.`;
  } else if (types4.length === 2) {
    msg += `one of type ${types4[0]} or ${types4[1]}.`;
  } else {
    msg += `of type ${types4[0]}.`;
  }
  if (actual == null) {
    msg += ` Received ${actual}`;
  } else if (typeof actual === "function" && actual.name) {
    msg += ` Received function ${actual.name}`;
  } else if (typeof actual === "object" && actual != null) {
    if (actual.constructor?.name) {
      msg += ` Received an instance of ${actual.constructor.name}`;
    }
  }
  return msg;
}
var invalid_key_input_default = (actual, ...types4) => {
  return message("Key must be ", actual, ...types4);
};
function withAlg(alg, actual, ...types4) {
  return message(`Key for the ${alg} algorithm must be `, actual, ...types4);
}

// node_modules/jose/dist/node/esm/runtime/is_key_like.js
var is_key_like_default = (key) => is_key_object_default(key) || isCryptoKey(key);
var types3 = ["KeyObject"];
if (globalThis.CryptoKey || webcrypto_default?.CryptoKey) {
  types3.push("CryptoKey");
}

// node_modules/jose/dist/node/esm/lib/is_disjoint.js
var isDisjoint = (...headers) => {
  const sources = headers.filter(Boolean);
  if (sources.length === 0 || sources.length === 1) {
    return true;
  }
  let acc;
  for (const header2 of sources) {
    const parameters = Object.keys(header2);
    if (!acc || acc.size === 0) {
      acc = new Set(parameters);
      continue;
    }
    for (const parameter of parameters) {
      if (acc.has(parameter)) {
        return false;
      }
      acc.add(parameter);
    }
  }
  return true;
};
var is_disjoint_default = isDisjoint;

// node_modules/jose/dist/node/esm/lib/is_object.js
function isObjectLike(value) {
  return typeof value === "object" && value !== null;
}
function isObject(input) {
  if (!isObjectLike(input) || Object.prototype.toString.call(input) !== "[object Object]") {
    return false;
  }
  if (Object.getPrototypeOf(input) === null) {
    return true;
  }
  let proto = input;
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto);
  }
  return Object.getPrototypeOf(input) === proto;
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
import { KeyObject } from "node:crypto";

// node_modules/jose/dist/node/esm/lib/is_jwk.js
function isJWK(key) {
  return isObject(key) && typeof key.kty === "string";
}
function isPrivateJWK(key) {
  return key.kty !== "oct" && typeof key.d === "string";
}
function isPublicJWK(key) {
  return key.kty !== "oct" && typeof key.d === "undefined";
}
function isSecretJWK(key) {
  return isJWK(key) && key.kty === "oct" && typeof key.k === "string";
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
var namedCurveToJOSE = (namedCurve) => {
  switch (namedCurve) {
    case "prime256v1":
      return "P-256";
    case "secp384r1":
      return "P-384";
    case "secp521r1":
      return "P-521";
    case "secp256k1":
      return "secp256k1";
    default:
      throw new JOSENotSupported("Unsupported key curve for this operation");
  }
};
var getNamedCurve2 = (kee, raw) => {
  let key;
  if (isCryptoKey(kee)) {
    key = KeyObject.from(kee);
  } else if (is_key_object_default(kee)) {
    key = kee;
  } else if (isJWK(kee)) {
    return kee.crv;
  } else {
    throw new TypeError(invalid_key_input_default(kee, ...types3));
  }
  if (key.type === "secret") {
    throw new TypeError('only "private" or "public" type keys can be used for this operation');
  }
  switch (key.asymmetricKeyType) {
    case "ed25519":
    case "ed448":
      return `Ed${key.asymmetricKeyType.slice(2)}`;
    case "x25519":
    case "x448":
      return `X${key.asymmetricKeyType.slice(1)}`;
    case "ec": {
      const namedCurve = key.asymmetricKeyDetails.namedCurve;
      if (raw) {
        return namedCurve;
      }
      return namedCurveToJOSE(namedCurve);
    }
    default:
      throw new TypeError("Invalid asymmetric key type for this operation");
  }
};
var get_named_curve_default = getNamedCurve2;

// node_modules/jose/dist/node/esm/runtime/check_key_length.js
import { KeyObject as KeyObject2 } from "node:crypto";
var check_key_length_default = (key, alg) => {
  let modulusLength;
  try {
    if (key instanceof KeyObject2) {
      modulusLength = key.asymmetricKeyDetails?.modulusLength;
    } else {
      modulusLength = Buffer.from(key.n, "base64url").byteLength << 3;
    }
  } catch {
  }
  if (typeof modulusLength !== "number" || modulusLength < 2048) {
    throw new TypeError(`${alg} requires key modulusLength to be 2048 bits or larger`);
  }
};

// node_modules/jose/dist/node/esm/runtime/asn1.js
import { createPrivateKey, createPublicKey, KeyObject as KeyObject3 } from "node:crypto";
import { Buffer as Buffer3 } from "node:buffer";
var fromPKCS8 = (pem2) => createPrivateKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PRIVATE KEY-----|\s)/g, ""), "base64"),
  type: "pkcs8",
  format: "der"
});
var fromSPKI = (pem2) => createPublicKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, ""), "base64"),
  type: "spki",
  format: "der"
});

// node_modules/jose/dist/node/esm/runtime/jwk_to_key.js
import { createPrivateKey as createPrivateKey2, createPublicKey as createPublicKey2 } from "node:crypto";
var parse = (key) => {
  if (key.d) {
    return createPrivateKey2({ format: "jwk", key });
  }
  return createPublicKey2({ format: "jwk", key });
};
var jwk_to_key_default = parse;

// node_modules/jose/dist/node/esm/key/import.js
async function importSPKI(spki, alg, options) {
  if (typeof spki !== "string" || spki.indexOf("-----BEGIN PUBLIC KEY-----") !== 0) {
    throw new TypeError('"spki" must be SPKI formatted string');
  }
  return fromSPKI(spki, alg, options);
}
async function importPKCS8(pkcs8, alg, options) {
  if (typeof pkcs8 !== "string" || pkcs8.indexOf("-----BEGIN PRIVATE KEY-----") !== 0) {
    throw new TypeError('"pkcs8" must be PKCS#8 formatted string');
  }
  return fromPKCS8(pkcs8, alg, options);
}
async function importJWK(jwk, alg) {
  if (!isObject(jwk)) {
    throw new TypeError("JWK must be an object");
  }
  alg ||= jwk.alg;
  switch (jwk.kty) {
    case "oct":
      if (typeof jwk.k !== "string" || !jwk.k) {
        throw new TypeError('missing "k" (Key Value) Parameter value');
      }
      return decode(jwk.k);
    case "RSA":
      if ("oth" in jwk && jwk.oth !== void 0) {
        throw new JOSENotSupported('RSA JWK "oth" (Other Primes Info) Parameter value is not supported');
      }
    case "EC":
    case "OKP":
      return jwk_to_key_default({ ...jwk, alg });
    default:
      throw new JOSENotSupported('Unsupported "kty" (Key Type) Parameter value');
  }
}

// node_modules/jose/dist/node/esm/lib/check_key_type.js
var tag = (key) => key?.[Symbol.toStringTag];
var jwkMatchesOp = (alg, key, usage) => {
  if (key.use !== void 0 && key.use !== "sig") {
    throw new TypeError("Invalid key for this operation, when present its use must be sig");
  }
  if (key.key_ops !== void 0 && key.key_ops.includes?.(usage) !== true) {
    throw new TypeError(`Invalid key for this operation, when present its key_ops must include ${usage}`);
  }
  if (key.alg !== void 0 && key.alg !== alg) {
    throw new TypeError(`Invalid key for this operation, when present its alg must be ${alg}`);
  }
  return true;
};
var symmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (key instanceof Uint8Array)
    return;
  if (allowJwk && isJWK(key)) {
    if (isSecretJWK(key) && jwkMatchesOp(alg, key, usage))
      return;
    throw new TypeError(`JSON Web Key for symmetric algorithms must have JWK "kty" (Key Type) equal to "oct" and the JWK "k" (Key Value) present`);
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, "Uint8Array", allowJwk ? "JSON Web Key" : null));
  }
  if (key.type !== "secret") {
    throw new TypeError(`${tag(key)} instances for symmetric algorithms must be of type "secret"`);
  }
};
var asymmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (allowJwk && isJWK(key)) {
    switch (usage) {
      case "sign":
        if (isPrivateJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a private JWK`);
      case "verify":
        if (isPublicJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a public JWK`);
    }
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, allowJwk ? "JSON Web Key" : null));
  }
  if (key.type === "secret") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
  }
  if (usage === "sign" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm signing must be of type "private"`);
  }
  if (usage === "decrypt" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm decryption must be of type "private"`);
  }
  if (key.algorithm && usage === "verify" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm verifying must be of type "public"`);
  }
  if (key.algorithm && usage === "encrypt" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm encryption must be of type "public"`);
  }
};
function checkKeyType(allowJwk, alg, key, usage) {
  const symmetric = alg.startsWith("HS") || alg === "dir" || alg.startsWith("PBES2") || /^A\d{3}(?:GCM)?KW$/.test(alg);
  if (symmetric) {
    symmetricTypeCheck(alg, key, usage, allowJwk);
  } else {
    asymmetricTypeCheck(alg, key, usage, allowJwk);
  }
}
var check_key_type_default = checkKeyType.bind(void 0, false);
var checkKeyTypeWithJwk = checkKeyType.bind(void 0, true);

// node_modules/jose/dist/node/esm/lib/validate_crit.js
function validateCrit(Err, recognizedDefault, recognizedOption, protectedHeader, joseHeader) {
  if (joseHeader.crit !== void 0 && protectedHeader?.crit === void 0) {
    throw new Err('"crit" (Critical) Header Parameter MUST be integrity protected');
  }
  if (!protectedHeader || protectedHeader.crit === void 0) {
    return /* @__PURE__ */ new Set();
  }
  if (!Array.isArray(protectedHeader.crit) || protectedHeader.crit.length === 0 || protectedHeader.crit.some((input) => typeof input !== "string" || input.length === 0)) {
    throw new Err('"crit" (Critical) Header Parameter MUST be an array of non-empty strings when present');
  }
  let recognized;
  if (recognizedOption !== void 0) {
    recognized = new Map([...Object.entries(recognizedOption), ...recognizedDefault.entries()]);
  } else {
    recognized = recognizedDefault;
  }
  for (const parameter of protectedHeader.crit) {
    if (!recognized.has(parameter)) {
      throw new JOSENotSupported(`Extension Header Parameter "${parameter}" is not recognized`);
    }
    if (joseHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" is missing`);
    }
    if (recognized.get(parameter) && protectedHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" MUST be integrity protected`);
    }
  }
  return new Set(protectedHeader.crit);
}
var validate_crit_default = validateCrit;

// node_modules/jose/dist/node/esm/lib/validate_algorithms.js
var validateAlgorithms = (option, algorithms) => {
  if (algorithms !== void 0 && (!Array.isArray(algorithms) || algorithms.some((s) => typeof s !== "string"))) {
    throw new TypeError(`"${option}" option must be an array of strings`);
  }
  if (!algorithms) {
    return void 0;
  }
  return new Set(algorithms);
};
var validate_algorithms_default = validateAlgorithms;

// node_modules/jose/dist/node/esm/runtime/verify.js
import * as crypto3 from "node:crypto";
import { promisify as promisify2 } from "node:util";

// node_modules/jose/dist/node/esm/runtime/dsa_digest.js
function dsaDigest(alg) {
  switch (alg) {
    case "PS256":
    case "RS256":
    case "ES256":
    case "ES256K":
      return "sha256";
    case "PS384":
    case "RS384":
    case "ES384":
      return "sha384";
    case "PS512":
    case "RS512":
    case "ES512":
      return "sha512";
    case "Ed25519":
    case "EdDSA":
      return void 0;
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/node_key.js
import { constants, KeyObject as KeyObject4 } from "node:crypto";
var ecCurveAlgMap = /* @__PURE__ */ new Map([
  ["ES256", "P-256"],
  ["ES256K", "secp256k1"],
  ["ES384", "P-384"],
  ["ES512", "P-521"]
]);
function keyForCrypto(alg, key) {
  let asymmetricKeyType;
  let asymmetricKeyDetails;
  let isJWK2;
  if (key instanceof KeyObject4) {
    asymmetricKeyType = key.asymmetricKeyType;
    asymmetricKeyDetails = key.asymmetricKeyDetails;
  } else {
    isJWK2 = true;
    switch (key.kty) {
      case "RSA":
        asymmetricKeyType = "rsa";
        break;
      case "EC":
        asymmetricKeyType = "ec";
        break;
      case "OKP": {
        if (key.crv === "Ed25519") {
          asymmetricKeyType = "ed25519";
          break;
        }
        if (key.crv === "Ed448") {
          asymmetricKeyType = "ed448";
          break;
        }
        throw new TypeError("Invalid key for this operation, its crv must be Ed25519 or Ed448");
      }
      default:
        throw new TypeError("Invalid key for this operation, its kty must be RSA, OKP, or EC");
    }
  }
  let options;
  switch (alg) {
    case "Ed25519":
      if (asymmetricKeyType !== "ed25519") {
        throw new TypeError(`Invalid key for this operation, its asymmetricKeyType must be ed25519`);
      }
      break;
    case "EdDSA":
      if (!["ed25519", "ed448"].includes(asymmetricKeyType)) {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ed25519 or ed448");
      }
      break;
    case "RS256":
    case "RS384":
    case "RS512":
      if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa");
      }
      check_key_length_default(key, alg);
      break;
    case "PS256":
    case "PS384":
    case "PS512":
      if (asymmetricKeyType === "rsa-pss") {
        const { hashAlgorithm, mgf1HashAlgorithm, saltLength } = asymmetricKeyDetails;
        const length = parseInt(alg.slice(-3), 10);
        if (hashAlgorithm !== void 0 && (hashAlgorithm !== `sha${length}` || mgf1HashAlgorithm !== hashAlgorithm)) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameters do not meet the requirements of "alg" ${alg}`);
        }
        if (saltLength !== void 0 && saltLength > length >> 3) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameter saltLength does not meet the requirements of "alg" ${alg}`);
        }
      } else if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa or rsa-pss");
      }
      check_key_length_default(key, alg);
      options = {
        padding: constants.RSA_PKCS1_PSS_PADDING,
        saltLength: constants.RSA_PSS_SALTLEN_DIGEST
      };
      break;
    case "ES256":
    case "ES256K":
    case "ES384":
    case "ES512": {
      if (asymmetricKeyType !== "ec") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ec");
      }
      const actual = get_named_curve_default(key);
      const expected = ecCurveAlgMap.get(alg);
      if (actual !== expected) {
        throw new TypeError(`Invalid key curve for the algorithm, its curve must be ${expected}, got ${actual}`);
      }
      options = { dsaEncoding: "ieee-p1363" };
      break;
    }
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
  if (isJWK2) {
    return { format: "jwk", key, ...options };
  }
  return options ? { ...options, key } : key;
}

// node_modules/jose/dist/node/esm/runtime/sign.js
import * as crypto2 from "node:crypto";
import { promisify } from "node:util";

// node_modules/jose/dist/node/esm/runtime/hmac_digest.js
function hmacDigest(alg) {
  switch (alg) {
    case "HS256":
      return "sha256";
    case "HS384":
      return "sha384";
    case "HS512":
      return "sha512";
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/get_sign_verify_key.js
import { KeyObject as KeyObject5, createSecretKey } from "node:crypto";
function getSignVerifyKey(alg, key, usage) {
  if (key instanceof Uint8Array) {
    if (!alg.startsWith("HS")) {
      throw new TypeError(invalid_key_input_default(key, ...types3));
    }
    return createSecretKey(key);
  }
  if (key instanceof KeyObject5) {
    return key;
  }
  if (isCryptoKey(key)) {
    checkSigCryptoKey(key, alg, usage);
    return KeyObject5.from(key);
  }
  if (isJWK(key)) {
    if (alg.startsWith("HS")) {
      return createSecretKey(Buffer.from(key.k, "base64url"));
    }
    return key;
  }
  throw new TypeError(invalid_key_input_default(key, ...types3, "Uint8Array", "JSON Web Key"));
}

// node_modules/jose/dist/node/esm/runtime/sign.js
var oneShotSign = promisify(crypto2.sign);
var sign2 = async (alg, key, data) => {
  const k = getSignVerifyKey(alg, key, "sign");
  if (alg.startsWith("HS")) {
    const hmac = crypto2.createHmac(hmacDigest(alg), k);
    hmac.update(data);
    return hmac.digest();
  }
  return oneShotSign(dsaDigest(alg), data, keyForCrypto(alg, k));
};
var sign_default = sign2;

// node_modules/jose/dist/node/esm/runtime/verify.js
var oneShotVerify = promisify2(crypto3.verify);
var verify2 = async (alg, key, signature, data) => {
  const k = getSignVerifyKey(alg, key, "verify");
  if (alg.startsWith("HS")) {
    const expected = await sign_default(alg, k, data);
    const actual = signature;
    try {
      return crypto3.timingSafeEqual(actual, expected);
    } catch {
      return false;
    }
  }
  const algorithm = dsaDigest(alg);
  const keyInput = keyForCrypto(alg, k);
  try {
    return await oneShotVerify(algorithm, data, keyInput, signature);
  } catch {
    return false;
  }
};
var verify_default = verify2;

// node_modules/jose/dist/node/esm/jws/flattened/verify.js
async function flattenedVerify(jws, key, options) {
  if (!isObject(jws)) {
    throw new JWSInvalid("Flattened JWS must be an object");
  }
  if (jws.protected === void 0 && jws.header === void 0) {
    throw new JWSInvalid('Flattened JWS must have either of the "protected" or "header" members');
  }
  if (jws.protected !== void 0 && typeof jws.protected !== "string") {
    throw new JWSInvalid("JWS Protected Header incorrect type");
  }
  if (jws.payload === void 0) {
    throw new JWSInvalid("JWS Payload missing");
  }
  if (typeof jws.signature !== "string") {
    throw new JWSInvalid("JWS Signature missing or incorrect type");
  }
  if (jws.header !== void 0 && !isObject(jws.header)) {
    throw new JWSInvalid("JWS Unprotected Header incorrect type");
  }
  let parsedProt = {};
  if (jws.protected) {
    try {
      const protectedHeader = decode(jws.protected);
      parsedProt = JSON.parse(decoder.decode(protectedHeader));
    } catch {
      throw new JWSInvalid("JWS Protected Header is invalid");
    }
  }
  if (!is_disjoint_default(parsedProt, jws.header)) {
    throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
  }
  const joseHeader = {
    ...parsedProt,
    ...jws.header
  };
  const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, parsedProt, joseHeader);
  let b64 = true;
  if (extensions.has("b64")) {
    b64 = parsedProt.b64;
    if (typeof b64 !== "boolean") {
      throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
    }
  }
  const { alg } = joseHeader;
  if (typeof alg !== "string" || !alg) {
    throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
  }
  const algorithms = options && validate_algorithms_default("algorithms", options.algorithms);
  if (algorithms && !algorithms.has(alg)) {
    throw new JOSEAlgNotAllowed('"alg" (Algorithm) Header Parameter value not allowed');
  }
  if (b64) {
    if (typeof jws.payload !== "string") {
      throw new JWSInvalid("JWS Payload must be a string");
    }
  } else if (typeof jws.payload !== "string" && !(jws.payload instanceof Uint8Array)) {
    throw new JWSInvalid("JWS Payload must be a string or an Uint8Array instance");
  }
  let resolvedKey = false;
  if (typeof key === "function") {
    key = await key(parsedProt, jws);
    resolvedKey = true;
    checkKeyTypeWithJwk(alg, key, "verify");
    if (isJWK(key)) {
      key = await importJWK(key, alg);
    }
  } else {
    checkKeyTypeWithJwk(alg, key, "verify");
  }
  const data = concat(encoder.encode(jws.protected ?? ""), encoder.encode("."), typeof jws.payload === "string" ? encoder.encode(jws.payload) : jws.payload);
  let signature;
  try {
    signature = decode(jws.signature);
  } catch {
    throw new JWSInvalid("Failed to base64url decode the signature");
  }
  const verified = await verify_default(alg, key, signature, data);
  if (!verified) {
    throw new JWSSignatureVerificationFailed();
  }
  let payload;
  if (b64) {
    try {
      payload = decode(jws.payload);
    } catch {
      throw new JWSInvalid("Failed to base64url decode the payload");
    }
  } else if (typeof jws.payload === "string") {
    payload = encoder.encode(jws.payload);
  } else {
    payload = jws.payload;
  }
  const result = { payload };
  if (jws.protected !== void 0) {
    result.protectedHeader = parsedProt;
  }
  if (jws.header !== void 0) {
    result.unprotectedHeader = jws.header;
  }
  if (resolvedKey) {
    return { ...result, key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/compact/verify.js
async function compactVerify(jws, key, options) {
  if (jws instanceof Uint8Array) {
    jws = decoder.decode(jws);
  }
  if (typeof jws !== "string") {
    throw new JWSInvalid("Compact JWS must be a string or Uint8Array");
  }
  const { 0: protectedHeader, 1: payload, 2: signature, length } = jws.split(".");
  if (length !== 3) {
    throw new JWSInvalid("Invalid Compact JWS");
  }
  const verified = await flattenedVerify({ payload, protected: protectedHeader, signature }, key, options);
  const result = { payload: verified.payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/lib/epoch.js
var epoch_default = (date) => Math.floor(date.getTime() / 1e3);

// node_modules/jose/dist/node/esm/lib/secs.js
var minute = 60;
var hour = minute * 60;
var day = hour * 24;
var week = day * 7;
var year = day * 365.25;
var REGEX = /^(\+|\-)? ?(\d+|\d+\.\d+) ?(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)(?: (ago|from now))?$/i;
var secs_default = (str) => {
  const matched = REGEX.exec(str);
  if (!matched || matched[4] && matched[1]) {
    throw new TypeError("Invalid time period format");
  }
  const value = parseFloat(matched[2]);
  const unit = matched[3].toLowerCase();
  let numericDate;
  switch (unit) {
    case "sec":
    case "secs":
    case "second":
    case "seconds":
    case "s":
      numericDate = Math.round(value);
      break;
    case "minute":
    case "minutes":
    case "min":
    case "mins":
    case "m":
      numericDate = Math.round(value * minute);
      break;
    case "hour":
    case "hours":
    case "hr":
    case "hrs":
    case "h":
      numericDate = Math.round(value * hour);
      break;
    case "day":
    case "days":
    case "d":
      numericDate = Math.round(value * day);
      break;
    case "week":
    case "weeks":
    case "w":
      numericDate = Math.round(value * week);
      break;
    default:
      numericDate = Math.round(value * year);
      break;
  }
  if (matched[1] === "-" || matched[4] === "ago") {
    return -numericDate;
  }
  return numericDate;
};

// node_modules/jose/dist/node/esm/lib/jwt_claims_set.js
var normalizeTyp = (value) => value.toLowerCase().replace(/^application\//, "");
var checkAudiencePresence = (audPayload, audOption) => {
  if (typeof audPayload === "string") {
    return audOption.includes(audPayload);
  }
  if (Array.isArray(audPayload)) {
    return audOption.some(Set.prototype.has.bind(new Set(audPayload)));
  }
  return false;
};
var jwt_claims_set_default = (protectedHeader, encodedPayload, options = {}) => {
  let payload;
  try {
    payload = JSON.parse(decoder.decode(encodedPayload));
  } catch {
  }
  if (!isObject(payload)) {
    throw new JWTInvalid("JWT Claims Set must be a top-level JSON object");
  }
  const { typ } = options;
  if (typ && (typeof protectedHeader.typ !== "string" || normalizeTyp(protectedHeader.typ) !== normalizeTyp(typ))) {
    throw new JWTClaimValidationFailed('unexpected "typ" JWT header value', payload, "typ", "check_failed");
  }
  const { requiredClaims = [], issuer, subject, audience, maxTokenAge } = options;
  const presenceCheck = [...requiredClaims];
  if (maxTokenAge !== void 0)
    presenceCheck.push("iat");
  if (audience !== void 0)
    presenceCheck.push("aud");
  if (subject !== void 0)
    presenceCheck.push("sub");
  if (issuer !== void 0)
    presenceCheck.push("iss");
  for (const claim of new Set(presenceCheck.reverse())) {
    if (!(claim in payload)) {
      throw new JWTClaimValidationFailed(`missing required "${claim}" claim`, payload, claim, "missing");
    }
  }
  if (issuer && !(Array.isArray(issuer) ? issuer : [issuer]).includes(payload.iss)) {
    throw new JWTClaimValidationFailed('unexpected "iss" claim value', payload, "iss", "check_failed");
  }
  if (subject && payload.sub !== subject) {
    throw new JWTClaimValidationFailed('unexpected "sub" claim value', payload, "sub", "check_failed");
  }
  if (audience && !checkAudiencePresence(payload.aud, typeof audience === "string" ? [audience] : audience)) {
    throw new JWTClaimValidationFailed('unexpected "aud" claim value', payload, "aud", "check_failed");
  }
  let tolerance;
  switch (typeof options.clockTolerance) {
    case "string":
      tolerance = secs_default(options.clockTolerance);
      break;
    case "number":
      tolerance = options.clockTolerance;
      break;
    case "undefined":
      tolerance = 0;
      break;
    default:
      throw new TypeError("Invalid clockTolerance option type");
  }
  const { currentDate } = options;
  const now = epoch_default(currentDate || /* @__PURE__ */ new Date());
  if ((payload.iat !== void 0 || maxTokenAge) && typeof payload.iat !== "number") {
    throw new JWTClaimValidationFailed('"iat" claim must be a number', payload, "iat", "invalid");
  }
  if (payload.nbf !== void 0) {
    if (typeof payload.nbf !== "number") {
      throw new JWTClaimValidationFailed('"nbf" claim must be a number', payload, "nbf", "invalid");
    }
    if (payload.nbf > now + tolerance) {
      throw new JWTClaimValidationFailed('"nbf" claim timestamp check failed', payload, "nbf", "check_failed");
    }
  }
  if (payload.exp !== void 0) {
    if (typeof payload.exp !== "number") {
      throw new JWTClaimValidationFailed('"exp" claim must be a number', payload, "exp", "invalid");
    }
    if (payload.exp <= now - tolerance) {
      throw new JWTExpired('"exp" claim timestamp check failed', payload, "exp", "check_failed");
    }
  }
  if (maxTokenAge) {
    const age = now - payload.iat;
    const max = typeof maxTokenAge === "number" ? maxTokenAge : secs_default(maxTokenAge);
    if (age - tolerance > max) {
      throw new JWTExpired('"iat" claim timestamp check failed (too far in the past)', payload, "iat", "check_failed");
    }
    if (age < 0 - tolerance) {
      throw new JWTClaimValidationFailed('"iat" claim timestamp check failed (it should be in the past)', payload, "iat", "check_failed");
    }
  }
  return payload;
};

// node_modules/jose/dist/node/esm/jwt/verify.js
async function jwtVerify(jwt, key, options) {
  const verified = await compactVerify(jwt, key, options);
  if (verified.protectedHeader.crit?.includes("b64") && verified.protectedHeader.b64 === false) {
    throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
  }
  const payload = jwt_claims_set_default(verified.protectedHeader, verified.payload, options);
  const result = { payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/flattened/sign.js
var FlattenedSign = class {
  _payload;
  _protectedHeader;
  _unprotectedHeader;
  constructor(payload) {
    if (!(payload instanceof Uint8Array)) {
      throw new TypeError("payload must be an instance of Uint8Array");
    }
    this._payload = payload;
  }
  setProtectedHeader(protectedHeader) {
    if (this._protectedHeader) {
      throw new TypeError("setProtectedHeader can only be called once");
    }
    this._protectedHeader = protectedHeader;
    return this;
  }
  setUnprotectedHeader(unprotectedHeader) {
    if (this._unprotectedHeader) {
      throw new TypeError("setUnprotectedHeader can only be called once");
    }
    this._unprotectedHeader = unprotectedHeader;
    return this;
  }
  async sign(key, options) {
    if (!this._protectedHeader && !this._unprotectedHeader) {
      throw new JWSInvalid("either setProtectedHeader or setUnprotectedHeader must be called before #sign()");
    }
    if (!is_disjoint_default(this._protectedHeader, this._unprotectedHeader)) {
      throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
    }
    const joseHeader = {
      ...this._protectedHeader,
      ...this._unprotectedHeader
    };
    const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, this._protectedHeader, joseHeader);
    let b64 = true;
    if (extensions.has("b64")) {
      b64 = this._protectedHeader.b64;
      if (typeof b64 !== "boolean") {
        throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
      }
    }
    const { alg } = joseHeader;
    if (typeof alg !== "string" || !alg) {
      throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
    }
    checkKeyTypeWithJwk(alg, key, "sign");
    let payload = this._payload;
    if (b64) {
      payload = encoder.encode(encode(payload));
    }
    let protectedHeader;
    if (this._protectedHeader) {
      protectedHeader = encoder.encode(encode(JSON.stringify(this._protectedHeader)));
    } else {
      protectedHeader = encoder.encode("");
    }
    const data = concat(protectedHeader, encoder.encode("."), payload);
    const signature = await sign_default(alg, key, data);
    const jws = {
      signature: encode(signature),
      payload: ""
    };
    if (b64) {
      jws.payload = decoder.decode(payload);
    }
    if (this._unprotectedHeader) {
      jws.header = this._unprotectedHeader;
    }
    if (this._protectedHeader) {
      jws.protected = decoder.decode(protectedHeader);
    }
    return jws;
  }
};

// node_modules/jose/dist/node/esm/jws/compact/sign.js
var CompactSign = class {
  _flattened;
  constructor(payload) {
    this._flattened = new FlattenedSign(payload);
  }
  setProtectedHeader(protectedHeader) {
    this._flattened.setProtectedHeader(protectedHeader);
    return this;
  }
  async sign(key, options) {
    const jws = await this._flattened.sign(key, options);
    if (jws.payload === void 0) {
      throw new TypeError("use the flattened module for creating JWS with b64: false");
    }
    return `${jws.protected}.${jws.payload}.${jws.signature}`;
  }
};

// node_modules/jose/dist/node/esm/jwt/produce.js
function validateInput(label, input) {
  if (!Number.isFinite(input)) {
    throw new TypeError(`Invalid ${label} input`);
  }
  return input;
}
var ProduceJWT = class {
  _payload;
  constructor(payload = {}) {
    if (!isObject(payload)) {
      throw new TypeError("JWT Claims Set MUST be an object");
    }
    this._payload = payload;
  }
  setIssuer(issuer) {
    this._payload = { ...this._payload, iss: issuer };
    return this;
  }
  setSubject(subject) {
    this._payload = { ...this._payload, sub: subject };
    return this;
  }
  setAudience(audience) {
    this._payload = { ...this._payload, aud: audience };
    return this;
  }
  setJti(jwtId) {
    this._payload = { ...this._payload, jti: jwtId };
    return this;
  }
  setNotBefore(input) {
    if (typeof input === "number") {
      this._payload = { ...this._payload, nbf: validateInput("setNotBefore", input) };
    } else if (input instanceof Date) {
      this._payload = { ...this._payload, nbf: validateInput("setNotBefore", epoch_default(input)) };
    } else {
      this._payload = { ...this._payload, nbf: epoch_default(/* @__PURE__ */ new Date()) + secs_default(input) };
    }
    return this;
  }
  setExpirationTime(input) {
    if (typeof input === "number") {
      this._payload = { ...this._payload, exp: validateInput("setExpirationTime", input) };
    } else if (input instanceof Date) {
      this._payload = { ...this._payload, exp: validateInput("setExpirationTime", epoch_default(input)) };
    } else {
      this._payload = { ...this._payload, exp: epoch_default(/* @__PURE__ */ new Date()) + secs_default(input) };
    }
    return this;
  }
  setIssuedAt(input) {
    if (typeof input === "undefined") {
      this._payload = { ...this._payload, iat: epoch_default(/* @__PURE__ */ new Date()) };
    } else if (input instanceof Date) {
      this._payload = { ...this._payload, iat: validateInput("setIssuedAt", epoch_default(input)) };
    } else if (typeof input === "string") {
      this._payload = {
        ...this._payload,
        iat: validateInput("setIssuedAt", epoch_default(/* @__PURE__ */ new Date()) + secs_default(input))
      };
    } else {
      this._payload = { ...this._payload, iat: validateInput("setIssuedAt", input) };
    }
    return this;
  }
};

// node_modules/jose/dist/node/esm/jwt/sign.js
var SignJWT = class extends ProduceJWT {
  _protectedHeader;
  setProtectedHeader(protectedHeader) {
    this._protectedHeader = protectedHeader;
    return this;
  }
  async sign(key, options) {
    const sig = new CompactSign(encoder.encode(JSON.stringify(this._payload)));
    sig.setProtectedHeader(this._protectedHeader);
    if (Array.isArray(this._protectedHeader?.crit) && this._protectedHeader.crit.includes("b64") && this._protectedHeader.b64 === false) {
      throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
    }
    return sig.sign(key, options);
  }
};

// packages/server-core/src/jwt.ts
var ALG = "EdDSA";
var ISSUER = "shikhon-lms";
function pem(envVar) {
  const v = process.env[envVar];
  if (!v) throw new Error(`${envVar} env var is not set`);
  return v.includes("\\n") ? v.replace(/\\n/g, "\n") : v;
}
var _privateKey = null;
var _publicKey = null;
function privateKey() {
  if (!_privateKey) _privateKey = importPKCS8(pem("JWT_PRIVATE_KEY"), ALG);
  return _privateKey;
}
function publicKey() {
  if (!_publicKey) _publicKey = importSPKI(pem("JWT_PUBLIC_KEY"), ALG);
  return _publicKey;
}
async function signAccessToken(claims, expiresIn = "15m") {
  const key = await privateKey();
  return new SignJWT({ tid: claims.tid, role: claims.role, roles: claims.roles }).setProtectedHeader({ alg: ALG }).setSubject(claims.sub).setIssuedAt().setIssuer(ISSUER).setExpirationTime(expiresIn).sign(key);
}
async function verifyAccessToken(token) {
  const key = await publicKey();
  const { payload } = await jwtVerify(token, key, { issuer: ISSUER });
  if (!payload.sub || !payload.tid || !payload.role) {
    throw new Error("access token missing required claims");
  }
  return {
    sub: payload.sub,
    tid: payload.tid,
    role: payload.role,
    roles: payload.roles ?? [payload.role]
  };
}

// services/identity-svc/src/roles.ts
async function loadRoles(client, tenantId, userId) {
  const { rows } = await client.query(
    `SELECT ur.role_code
       FROM user_roles ur
       JOIN roles r ON r.code = ur.role_code
       JOIN users u ON u.id = ur.user_id AND u.tenant_id = ur.tenant_id
      WHERE ur.tenant_id = $1 AND ur.user_id = $2
        AND (ur.valid_until IS NULL OR ur.valid_until >= app.today_dhaka())
        AND u.deleted_at IS NULL
        AND u.status IN ('active', 'invited')
      ORDER BY r.rank DESC`,
    [tenantId, userId]
  );
  if (rows.length === 0) return { primaryRole: "", roles: [] };
  return { primaryRole: rows[0].role_code, roles: rows.map((r) => r.role_code) };
}

// services/identity-svc/api/otp-verify.ts
var PHONE_RE2 = /^\+8801[3-9][0-9]{8}$/;
var REFRESH_TTL_DAYS = 30;
var ACCESS_TTL = "15m";
async function handler2(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const body = await readJson(req);
    const tenantId = body.tenantId ?? "";
    const phone = body.phone ?? "";
    const purpose = body.purpose ?? "login";
    const code = body.code ?? "";
    const deviceId = body.deviceId ?? "";
    const deviceLabel = body.deviceLabel ?? null;
    if (!tenantId) throw new HttpError(400, "tenantId is required", "tenant_required");
    if (!PHONE_RE2.test(phone)) throw new HttpError(400, "phone must be a valid +8801XXXXXXXXX number", "invalid_phone");
    if (!/^[0-9]{4,8}$/.test(code)) throw new HttpError(400, "code is required", "invalid_code_format");
    if (!deviceId) throw new HttpError(400, "deviceId is required", "device_required");
    if (!await enforceIdentityRateLimit(res, cors, "otp_verify", `${tenantId}:${phone}`)) return;
    const db = await sharedDb();
    const result = await db.withTenant({ tenantId, userId: "", role: "system_ingest" }, async (client) => {
      const challenge = await client.query(
        `SELECT id, code_hash, attempts, max_attempts FROM otp_challenges
          WHERE tenant_id = $1 AND phone_e164 = $2 AND purpose = $3
            AND consumed_at IS NULL AND expires_at > now()
          ORDER BY created_at DESC LIMIT 1
          FOR UPDATE`,
        [tenantId, phone, purpose]
      );
      const row = challenge.rows[0];
      if (!row) throw new HttpError(400, "no active OTP challenge found \u2014 request a new code", "challenge_not_found");
      if (row.attempts >= row.max_attempts) {
        throw new HttpError(429, "too many attempts \u2014 request a new code", "too_many_attempts");
      }
      const candidateHash = sha256Buf(code).toString("hex");
      const storedHash = Buffer.from(row.code_hash).toString("hex");
      if (!constantTimeEqualHex(candidateHash, storedHash)) {
        await client.query(`UPDATE otp_challenges SET attempts = attempts + 1 WHERE id = $1`, [row.id]);
        throw new HttpError(400, "incorrect code", "invalid_code");
      }
      await client.query(`UPDATE otp_challenges SET consumed_at = now() WHERE id = $1`, [row.id]);
      const userRes = await client.query(
        `SELECT id, full_name_en, full_name_bn, status FROM users
          WHERE tenant_id = $1 AND phone_e164 = $2 AND deleted_at IS NULL`,
        [tenantId, phone]
      );
      const user = userRes.rows[0];
      if (!user) throw new HttpError(404, "no account found for this phone number", "user_not_found");
      if (user.status !== "active" && user.status !== "invited") {
        throw new HttpError(403, `account is ${user.status}`, "account_not_active");
      }
      const { primaryRole, roles } = await loadRoles(client, tenantId, user.id);
      if (!primaryRole) throw new HttpError(403, "account has no active role assigned", "no_active_role");
      const refreshToken = randomOpaqueToken(32);
      const refreshHash = sha256Buf(refreshToken);
      await client.query(
        `INSERT INTO user_sessions (tenant_id, user_id, refresh_token_hash, device_id, device_label, expires_at)
         VALUES ($1, $2, $3, $4, $5, now() + ($6 || ' days')::interval)`,
        [tenantId, user.id, refreshHash, deviceId, deviceLabel, REFRESH_TTL_DAYS]
      );
      const accessToken = await signAccessToken({ sub: user.id, tid: tenantId, role: primaryRole, roles }, ACCESS_TTL);
      return {
        accessToken,
        refreshToken,
        expiresIn: 900,
        user: {
          id: user.id,
          fullNameEn: user.full_name_en,
          fullNameBn: user.full_name_bn,
          role: primaryRole,
          roles
        }
      };
    });
    json(res, 200, result, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[otp-verify] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/identity-svc/api/refresh.ts
var REFRESH_TTL_DAYS2 = 30;
var ACCESS_TTL2 = "15m";
async function handler3(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const body = await readJson(req);
    const tenantId = body.tenantId ?? "";
    const oldRefreshToken = body.refreshToken ?? "";
    const deviceId = body.deviceId ?? "";
    if (!tenantId) throw new HttpError(400, "tenantId is required", "tenant_required");
    if (!oldRefreshToken) throw new HttpError(400, "refreshToken is required", "refresh_token_required");
    const db = await sharedDb();
    const result = await db.withTenant({ tenantId, userId: "", role: "system_ingest" }, async (client) => {
      const oldHash = sha256Buf(oldRefreshToken);
      const sessionRes = await client.query(
        `SELECT id, user_id, device_label FROM user_sessions
          WHERE tenant_id = $1 AND refresh_token_hash = $2
            AND revoked_at IS NULL AND expires_at > now()
          FOR UPDATE`,
        [tenantId, oldHash]
      );
      const session = sessionRes.rows[0];
      if (!session) throw new HttpError(401, "refresh token is invalid or expired", "invalid_refresh_token");
      const accountRes = await client.query(
        `SELECT status::text AS status FROM users
          WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [session.user_id, tenantId]
      );
      const account = accountRes.rows[0];
      if (!account) throw new HttpError(403, "account no longer exists", "account_not_active");
      if (account.status !== "active" && account.status !== "invited") {
        throw new HttpError(403, `account is ${account.status}`, "account_not_active");
      }
      const { primaryRole, roles } = await loadRoles(client, tenantId, session.user_id);
      if (!primaryRole) throw new HttpError(403, "account has no active role assigned", "no_active_role");
      const newRefreshToken = randomOpaqueToken(32);
      const newHash = sha256Buf(newRefreshToken);
      const newSessionRes = await client.query(
        `INSERT INTO user_sessions (tenant_id, user_id, refresh_token_hash, device_id, device_label, expires_at)
         VALUES ($1, $2, $3, $4, $5, now() + ($6 || ' days')::interval)
         RETURNING id`,
        [tenantId, session.user_id, newHash, deviceId || null, session.device_label, REFRESH_TTL_DAYS2]
      );
      await client.query(
        `UPDATE user_sessions SET revoked_at = now(), revoked_reason = 'rotated', superseded_by = $2
          WHERE id = $1`,
        [session.id, newSessionRes.rows[0].id]
      );
      const accessToken = await signAccessToken(
        { sub: session.user_id, tid: tenantId, role: primaryRole, roles },
        ACCESS_TTL2
      );
      return { accessToken, refreshToken: newRefreshToken, expiresIn: 900 };
    }, { sessionWrite: true });
    json(res, 200, result, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[refresh] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/identity-svc/api/logout.ts
async function handler4(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const body = await readJson(req);
    const tenantId = body.tenantId ?? "";
    const refreshToken = body.refreshToken ?? "";
    if (!tenantId) throw new HttpError(400, "tenantId is required", "tenant_required");
    if (!refreshToken) throw new HttpError(400, "refreshToken is required", "refresh_token_required");
    const db = await sharedDb();
    await db.withTenant({ tenantId, userId: "", role: "system_ingest" }, async (client) => {
      await client.query(
        `UPDATE user_sessions SET revoked_at = now(), revoked_reason = 'logout'
          WHERE tenant_id = $1 AND refresh_token_hash = $2 AND revoked_at IS NULL`,
        [tenantId, sha256Buf(refreshToken)]
      );
    });
    json(res, 200, { ok: true }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[logout] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// packages/server-core/src/auth.ts
async function authenticate(req) {
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) throw new HttpError(401, "missing bearer token", "unauthorized");
  try {
    return await verifyAccessToken(token);
  } catch {
    throw new HttpError(401, "invalid or expired access token", "unauthorized");
  }
}
function requireRole(claims, allowed) {
  if (!allowed.includes(claims.role)) {
    throw new HttpError(403, `this endpoint requires one of: ${allowed.join(", ")}`, "forbidden");
  }
}

// services/identity-svc/src/activation.ts
import { createHmac as createHmac2, randomBytes as randomBytes2 } from "node:crypto";
var ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ2345678";
var CODE_LEN = 8;
function generateCode() {
  const bytes = randomBytes2(CODE_LEN);
  let out = "";
  for (let i = 0; i < CODE_LEN; i++) out += ALPHABET[bytes[i] % ALPHABET.length];
  return out;
}
function codeHash(code) {
  const pepper = process.env.ACTIVATION_PEPPER;
  const norm = code.toUpperCase().replace(/[^A-Z2-9]/g, "").replace(/0/g, "O").replace(/O/g, "Q").replace(/[1IL]/g, "J");
  return createHmac2("sha256", pepper).update(norm).digest();
}

// services/identity-svc/api/activate.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var ISSUER_ROLES = ["principal", "school_owner", "academic_coordinator", "class_teacher"];
var REFRESH_TTL_DAYS3 = 30;
var ACCESS_TTL3 = "15m";
async function handler5(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    if (!process.env.ACTIVATION_PEPPER || process.env.ACTIVATION_PEPPER.length < 16) {
      throw new HttpError(
        503,
        "activation is not configured on this deployment",
        "activation_unconfigured"
      );
    }
    const body = await readJson(req);
    if (body.action === "issue") {
      await issue(req, res, cors, body);
      return;
    }
    if (body.action === "redeem") {
      await redeem(res, cors, body);
      return;
    }
    throw new HttpError(400, "action must be 'issue' or 'redeem'", "invalid_action");
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    json(res, 500, { error: "internal_error" }, cors);
  }
}
async function issue(req, res, cors, body) {
  const claims = await authenticate(req);
  requireRole(claims, ISSUER_ROLES);
  const userId = body.userId ?? "";
  if (!UUID_RE.test(userId)) {
    throw new HttpError(400, "userId must be a valid uuid", "invalid_user_id");
  }
  const code = generateCode();
  const db = await sharedDb();
  const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
  const expiresAt = await db.withTenant(ctx, async (client) => {
    await client.query(
      `UPDATE activation_codes SET revoked_at = now()
        WHERE user_id = $1 AND used_at IS NULL AND revoked_at IS NULL`,
      [userId]
    );
    try {
      const r = await client.query(
        `INSERT INTO activation_codes (tenant_id, user_id, code_hash, issued_by)
         VALUES (app.current_tenant(), $1, $2, $3)
         RETURNING expires_at`,
        [userId, codeHash(code), claims.sub]
      );
      return r.rows[0].expires_at;
    } catch (err) {
      if (err.code === "42501") {
        throw new HttpError(
          403,
          "you may only issue activation codes for students of your own sections",
          "not_your_student"
        );
      }
      if (err.code === "23503") {
        throw new HttpError(404, "user not found", "user_not_found");
      }
      throw err;
    }
  });
  json(res, 200, { code, expiresAt }, cors);
}
async function redeem(res, cors, body) {
  const code = body.code ?? "";
  const deviceId = body.deviceId ?? "";
  const tenantId = body.tenantId ?? "";
  if (!UUID_RE.test(tenantId)) {
    throw new HttpError(400, "tenantId is required", "tenant_required");
  }
  if (code.replace(/[^A-Za-z0-9]/g, "").length < CODE_LEN) {
    throw new HttpError(400, "code is too short", "invalid_code_format");
  }
  if (!deviceId) throw new HttpError(400, "deviceId is required", "device_required");
  if (!await enforceIdentityRateLimit(res, cors, "otp_verify", `activate:${deviceId}`)) return;
  const hash = codeHash(code);
  const db = await sharedDb();
  const result = await db.withTenant(
    { tenantId, userId: "", role: "system_ingest" },
    async (client) => {
      const found = await client.query(
        `SELECT id, tenant_id, user_id, used_at, revoked_at,
              (expires_at <= now()) AS expired
         FROM activation_codes WHERE code_hash = $1 AND tenant_id = $2`,
        [hash, tenantId]
      );
      const row = found.rows[0];
      if (!row || row.used_at || row.revoked_at || row.expired) {
        throw new HttpError(
          400,
          "incorrect or expired code \u2014 ask your teacher for a new one",
          "invalid_code"
        );
      }
      await client.query(`SELECT set_config('app.user_id', $1, true)`, [row.user_id]);
      await client.query(
        `UPDATE activation_codes SET used_at = now() WHERE id = $1`,
        [row.id]
      );
      const userRes = await client.query(
        `SELECT id, full_name_en, full_name_bn, status FROM users
        WHERE id = $1 AND deleted_at IS NULL`,
        [row.user_id]
      );
      const user = userRes.rows[0];
      if (!user) throw new HttpError(404, "account no longer exists", "user_not_found");
      if (user.status !== "active" && user.status !== "invited") {
        throw new HttpError(403, `account is ${user.status}`, "account_not_active");
      }
      if (user.status === "invited") {
        await client.query(
          `UPDATE users SET status = 'active' WHERE id = $1`,
          [row.user_id]
        );
      }
      const { primaryRole, roles } = await loadRoles(client, row.tenant_id, user.id);
      if (!primaryRole) throw new HttpError(403, "account has no active role assigned", "no_active_role");
      const refreshToken = randomOpaqueToken(32);
      await client.query(
        `INSERT INTO user_sessions (tenant_id, user_id, refresh_token_hash, device_id, device_label, expires_at)
       VALUES ($1, $2, $3, $4, $5, now() + ($6 || ' days')::interval)`,
        [
          row.tenant_id,
          user.id,
          sha256Buf(refreshToken),
          deviceId,
          body.deviceLabel ?? null,
          REFRESH_TTL_DAYS3
        ]
      );
      const accessToken = await signAccessToken(
        { sub: user.id, tid: row.tenant_id, role: primaryRole, roles },
        ACCESS_TTL3
      );
      return {
        accessToken,
        refreshToken,
        expiresIn: 900,
        user: {
          id: user.id,
          fullNameEn: user.full_name_en,
          fullNameBn: user.full_name_bn,
          role: primaryRole,
          roles
        }
      };
    }
  );
  json(res, 200, result, cors);
}

// packages/server-core/src/audit.ts
async function writeAudit(client, actor, entry) {
  const sp = `audit_${Math.random().toString(36).slice(2, 10)}`;
  try {
    await client.query(`SAVEPOINT ${sp}`);
  } catch {
  }
  try {
    await client.query(
      `INSERT INTO audit.activity_log
         (tenant_id, actor_id, actor_role, action, entity_type, entity_id,
          before_state, after_state)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8::jsonb)`,
      [
        actor.tenantId,
        actor.userId,
        actor.role,
        entry.action,
        entry.entityType,
        entry.entityId ?? null,
        entry.before === void 0 ? null : JSON.stringify(entry.before),
        entry.after === void 0 ? null : JSON.stringify(entry.after)
      ]
    );
    try {
      await client.query(`RELEASE SAVEPOINT ${sp}`);
    } catch {
    }
  } catch {
    try {
      await client.query(`ROLLBACK TO SAVEPOINT ${sp}`);
    } catch {
    }
  }
}

// services/identity-svc/api/sessions.ts
function describe(r) {
  if (r.device_label && r.device_label.trim()) return r.device_label.trim();
  const ua = r.user_agent ?? "";
  const browser = /Edg\//.test(ua) ? "Edge" : /OPR\//.test(ua) ? "Opera" : /Chrome\//.test(ua) ? "Chrome" : /Firefox\//.test(ua) ? "Firefox" : /Safari\//.test(ua) ? "Safari" : "";
  const os = /Android/.test(ua) ? "Android" : /iPhone|iPad|iOS/.test(ua) ? "iOS" : /Windows/.test(ua) ? "Windows" : /Mac OS X|Macintosh/.test(ua) ? "Mac" : /Linux/.test(ua) ? "Linux" : "";
  const parts = [browser, os].filter(Boolean);
  return parts.length ? parts.join(" \xB7 ") : "\u0985\u099C\u09BE\u09A8\u09BE \u09A1\u09BF\u09AD\u09BE\u0987\u09B8";
}
async function handler6(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  try {
    const claims = await authenticate(req);
    const db = await sharedDb();
    const actor = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    const path = new URL(req.url ?? "/", "http://internal").pathname;
    const isRevokeOthers = /revoke-others$/.test(path) || (query(req).get("path") ?? "") === "sessions/revoke-others";
    const isRevoke = !isRevokeOthers && (/revoke$/.test(path) || (query(req).get("path") ?? "") === "sessions/revoke");
    if (req.method === "GET" && !isRevoke && !isRevokeOthers) {
      const current = (query(req).get("deviceId") ?? "").trim();
      return json(res, 200, await list(db, actor, current), cors);
    }
    if (req.method !== "POST") {
      json(res, 405, { error: "method_not_allowed" }, cors);
      return;
    }
    const body = await readJson(req);
    const deviceId = (body.deviceId ?? "").trim();
    if (!deviceId) {
      throw new HttpError(400, "deviceId is required", "device_required");
    }
    if (isRevokeOthers) return json(res, 200, await revokeOthers(db, actor, deviceId), cors);
    if (isRevoke) return json(res, 200, await revokeOne(db, actor, deviceId), cors);
    json(res, 404, { error: "not_found" }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    json(res, 500, { error: "internal_error" }, cors);
  }
}
async function list(db, actor, currentDevice) {
  return db.withTenant(actor, async (c) => {
    const { rows } = await c.query(
      `SELECT DISTINCT ON (s.device_id)
              s.device_id, s.device_label, s.user_agent,
              s.issued_at::text     AS issued_at,
              s.last_seen_at::text  AS last_seen_at,
              s.expires_at::text    AS expires_at
         FROM user_sessions s
        WHERE s.user_id = $1
          AND s.revoked_at IS NULL
          AND s.expires_at > now()
        ORDER BY s.device_id, s.issued_at DESC`,
      [actor.userId]
    );
    return {
      sessions: rows.map((r) => ({
        // The device id is the handle the client passes back to revoke. It
        // is the client's OWN identifier, not a server secret, and it is the
        // only id here — no session row id, no token, no hash.
        deviceId: r.device_id,
        label: describe(r),
        current: !!r.device_id && r.device_id === currentDevice,
        signedInAt: r.issued_at,
        lastSeenAt: r.last_seen_at,
        expiresAt: r.expires_at
      }))
    };
  });
}
async function revokeOne(db, actor, deviceId) {
  return db.withTenant(actor, async (c) => {
    const { rowCount } = await c.query(
      `UPDATE user_sessions
          SET revoked_at = now(), revoked_reason = 'user_revoked'
        WHERE user_id = $1 AND device_id = $2 AND revoked_at IS NULL`,
      [actor.userId, deviceId]
    );
    const revoked = rowCount ?? 0;
    if (revoked > 0) {
      await writeAudit(c, actor, {
        action: "identity.session.revoke",
        entityType: "session",
        // The device, the count and the reason. Never a token, never a hash
        // — the row holds `refresh_token_hash` and it does not come near
        // this.
        after: { device: deviceId, sessions: revoked, scope: "one" }
      });
    }
    return { revoked };
  });
}
async function revokeOthers(db, actor, keepDevice) {
  return db.withTenant(actor, async (c) => {
    const { rowCount } = await c.query(
      `UPDATE user_sessions
          SET revoked_at = now(), revoked_reason = 'user_revoked_others'
        WHERE user_id = $1 AND revoked_at IS NULL
          AND (device_id IS DISTINCT FROM $2)`,
      [actor.userId, keepDevice]
    );
    const revoked = rowCount ?? 0;
    if (revoked > 0) {
      await writeAudit(c, actor, {
        action: "identity.session.revoke",
        entityType: "session",
        after: { kept: keepDevice, sessions: revoked, scope: "others" }
      });
    }
    return { revoked };
  });
}

// services/identity-svc/api/index.ts
var ROUTES = {
  "otp/request": handler,
  "otp/verify": handler2,
  "refresh": handler3,
  "logout": handler4,
  "activate": handler5,
  // One handler, three sub-paths: it needs the same authenticated identity
  // and the same device rule for all three, and splitting it would put that
  // rule in three files.
  "sessions": handler6,
  "sessions/revoke": handler6,
  "sessions/revoke-others": handler6
};
var LIMIT_CLASS = {
  "otp/request": "otp_request",
  "otp/verify": "otp_verify",
  "refresh": "auth",
  "logout": "auth",
  // Redemption is code-guessing surface, so it gets the strict OTP-verify
  // buckets; the identity dimension is charged inside the handler.
  "activate": "otp_verify",
  // Authenticated and cheap, but a revoke loop is still a write loop.
  "sessions": "read",
  "sessions/revoke": "mutation",
  "sessions/revoke-others": "mutation"
};
async function handler7(req, res) {
  const url = new URL(req.url ?? "/", "http://internal");
  const sub = (url.searchParams.get("path") ?? url.pathname.replace(/^\/api\/v1\/auth\/?/, "")).replace(/\/+$/, "");
  const route = ROUTES[sub];
  if (!route) {
    json(res, 404, { error: "not_found" }, corsHeaders());
    return;
  }
  if (req.method !== "OPTIONS" && !await enforceRateLimit(req, res, corsHeaders(), LIMIT_CLASS[sub])) return;
  return route(req, res);
}
export {
  handler7 as default
};
