// GENERATED by scripts/build.mjs from services/finance-svc/api/index.ts — do not edit directly.

// packages/server-core/src/db.ts
import pg from "pg";

// packages/server-core/src/http.ts
function allowedOrigins(env = process.env) {
  return (env.ALLOWED_ORIGINS ?? "").split(",").map((o) => o.trim()).filter((o) => o.length > 0);
}
function corsOriginFor(requestOrigin, env = process.env) {
  const allow = allowedOrigins(env);
  if (allow.length === 0) return { origin: "*", vary: false };
  if (requestOrigin && allow.includes(requestOrigin)) {
    return { origin: requestOrigin, vary: true };
  }
  return { origin: allow[0], vary: true };
}
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS", requestOrigin) {
  const { origin, vary } = corsOriginFor(requestOrigin);
  return {
    ...vary ? { Vary: "Origin" } : {},
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
async function readJson(req) {
  const raw = await readBody(req);
  return JSON.parse(raw);
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}
var HttpError = class extends Error {
  // Longhand rather than constructor parameter properties: node --test
  // strips types instead of compiling them, and parameter properties are the
  // one TS-only construct it cannot strip. Since every server module reaches
  // this file, that single construct made all of server-core un-testable
  // under the project's `node --test file.ts` convention.
  status;
  code;
  /**
   * Structured context spread into the error body alongside `error` and
   * `message`. For refusals a screen has to act on rather than merely print —
   * the routine editor naming the class that already owns an hour, say — a
   * sentence is what the user reads and this is what the UI renders. Optional
   * everywhere; an endpoint that has nothing to add omits it.
   */
  detail;
  constructor(status, message2, code, detail) {
    super(message2);
    this.status = status;
    this.code = code;
    this.detail = detail;
  }
};
var TenantBlocked = class extends HttpError {
  access;
  /**
   * The same sentence as `message`, under the name the rest of the product
   * uses for a Bangla string meant for a person. `message` is what a log
   * shows; this is what a screen shows, and keeping both makes it obvious at
   * a call site which one is being read.
   */
  reasonBn;
  constructor(access) {
    super(
      403,
      access.reasonBn ?? "\u098F\u0987 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u09C7\u09B0 \u0985\u09CD\u09AF\u09BE\u0995\u09BE\u0989\u09A8\u09CD\u099F\u09C7 \u098F\u0996\u09A8 \u098F\u0987 \u0995\u09BE\u099C\u099F\u09BF \u0995\u09B0\u09BE \u09AF\u09BE\u099A\u09CD\u099B\u09C7 \u09A8\u09BE\u0964",
      "tenant_blocked",
      {
        access: access.access,
        opsState: access.opsState,
        billingState: access.billingState,
        until: access.until,
        // B-84. Present only when a service was named. `not_in_plan` means
        // buy it; `disabled` and `maintenance` mean wait or ring us. Those
        // are different errands for the office and the screen must be able
        // to send them on the right one.
        ...access.serviceState ? { serviceState: access.serviceState } : {}
      }
    );
    this.access = access;
    this.reasonBn = this.message;
  }
};

// packages/server-core/src/db.ts
pg.types.setTypeParser(1082, (v) => v);
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    let readOnlyFor;
    let released = false;
    try {
      await client.query("BEGIN");
      readOnlyFor = (await setup(client))?.blocked;
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      if (readOnlyFor && err?.code === "25006") {
        try {
          await client.query("ROLLBACK");
        } catch {
        }
        client.release();
        released = true;
        throw new TenantBlocked(readOnlyFor);
      }
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      if (!released) client.release();
    }
  }
  return {
    pool,
    async tenantAccess(tenantId) {
      return readAccess(pool, tenantId);
    },
    withTenant(ctx, fn, opts2) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        let blocked;
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
        if (opts2?.skipGate) return;
        const access = await readAccess(c, ctx.tenantId, ctx.role, ctx.service);
        if (access.access === "none") {
          if (ctx.service) {
            const { rows } = await c.query(
              "SELECT app.tenant_service_state($1, $2) AS state",
              [ctx.tenantId, ctx.service]
            );
            const state = rows[0]?.state;
            if (state) throw new TenantBlocked({ ...access, serviceState: state });
          }
          throw new TenantBlocked(access);
        }
        if (access.access === "read_only") {
          if (opts2?.sessionWrite) return { blocked: void 0 };
          await c.query("SET LOCAL transaction_read_only = on");
          blocked = access;
          if (opts2?.write) throw new TenantBlocked(access);
        }
        return { blocked };
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function readAccess(q, tenantId, role, service) {
  try {
    const { rows } = role && service ? await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1, $2, $3)`,
      [tenantId, role, service]
    ) : role ? await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1, $2)`,
      [tenantId, role]
    ) : await q.query(
      `SELECT access, ops_state, billing_state, reason_bn, until
           FROM app.tenant_access($1)`,
      [tenantId]
    );
    const r = rows[0];
    if (!r?.access) {
      return {
        access: "none",
        opsState: "unknown",
        billingState: "unknown",
        reasonBn: "\u098F\u0987 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u099F\u09BF \u0996\u09C1\u0981\u099C\u09C7 \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964",
        until: null
      };
    }
    return {
      access: r.access,
      opsState: r.ops_state ?? "unknown",
      billingState: r.billing_state ?? "unknown",
      reasonBn: r.reason_bn ?? null,
      until: r.until ? String(r.until).slice(0, 10) : null
    };
  } catch {
    return {
      access: "none",
      opsState: "unknown",
      billingState: "unknown",
      reasonBn: "\u09AA\u09CD\u09B0\u09A4\u09BF\u09B7\u09CD\u09A0\u09BE\u09A8\u09C7\u09B0 \u0985\u09AC\u09B8\u09CD\u09A5\u09BE \u09AF\u09BE\u099A\u09BE\u0987 \u0995\u09B0\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964 \u098F\u0995\u099F\u09C1 \u09AA\u09B0\u09C7 \u0986\u09AC\u09BE\u09B0 \u099A\u09C7\u09B7\u09CD\u099F\u09BE \u0995\u09B0\u09C1\u09A8\u0964",
      until: null
    };
  }
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/go-live.ts
function enabled(name, env = process.env) {
  return (env[name] ?? "").trim().toLowerCase() === "true";
}
function mfsPaymentsEnabled(env = process.env) {
  return enabled("MFS_PAYMENTS_ENABLED", env);
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
import { Buffer as Buffer2 } from "node:buffer";

// node_modules/jose/dist/node/esm/lib/buffer_utils.js
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var MAX_INT32 = 2 ** 32;
function concat(...buffers) {
  const size = buffers.reduce((acc, { length }) => acc + length, 0);
  const buf = new Uint8Array(size);
  let i = 0;
  for (const buffer of buffers) {
    buf.set(buffer, i);
    i += buffer.length;
  }
  return buf;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
function normalize(input) {
  let encoded = input;
  if (encoded instanceof Uint8Array) {
    encoded = decoder.decode(encoded);
  }
  return encoded;
}
var decode = (input) => new Uint8Array(Buffer2.from(normalize(input), "base64url"));

// node_modules/jose/dist/node/esm/util/errors.js
var JOSEError = class extends Error {
  static code = "ERR_JOSE_GENERIC";
  code = "ERR_JOSE_GENERIC";
  constructor(message2, options) {
    super(message2, options);
    this.name = this.constructor.name;
    Error.captureStackTrace?.(this, this.constructor);
  }
};
var JWTClaimValidationFailed = class extends JOSEError {
  static code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JWTExpired = class extends JOSEError {
  static code = "ERR_JWT_EXPIRED";
  code = "ERR_JWT_EXPIRED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JOSEAlgNotAllowed = class extends JOSEError {
  static code = "ERR_JOSE_ALG_NOT_ALLOWED";
  code = "ERR_JOSE_ALG_NOT_ALLOWED";
};
var JOSENotSupported = class extends JOSEError {
  static code = "ERR_JOSE_NOT_SUPPORTED";
  code = "ERR_JOSE_NOT_SUPPORTED";
};
var JWSInvalid = class extends JOSEError {
  static code = "ERR_JWS_INVALID";
  code = "ERR_JWS_INVALID";
};
var JWTInvalid = class extends JOSEError {
  static code = "ERR_JWT_INVALID";
  code = "ERR_JWT_INVALID";
};
var JWSSignatureVerificationFailed = class extends JOSEError {
  static code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  constructor(message2 = "signature verification failed", options) {
    super(message2, options);
  }
};

// node_modules/jose/dist/node/esm/runtime/is_key_object.js
import * as util from "node:util";
var is_key_object_default = (obj) => util.types.isKeyObject(obj);

// node_modules/jose/dist/node/esm/runtime/webcrypto.js
import * as crypto from "node:crypto";
import * as util2 from "node:util";
var webcrypto2 = crypto.webcrypto;
var webcrypto_default = webcrypto2;
var isCryptoKey = (key) => util2.types.isCryptoKey(key);

// node_modules/jose/dist/node/esm/lib/crypto_key.js
function unusable(name, prop = "algorithm.name") {
  return new TypeError(`CryptoKey does not support this operation, its ${prop} must be ${name}`);
}
function isAlgorithm(algorithm, name) {
  return algorithm.name === name;
}
function getHashLength(hash) {
  return parseInt(hash.name.slice(4), 10);
}
function getNamedCurve(alg) {
  switch (alg) {
    case "ES256":
      return "P-256";
    case "ES384":
      return "P-384";
    case "ES512":
      return "P-521";
    default:
      throw new Error("unreachable");
  }
}
function checkUsage(key, usages) {
  if (usages.length && !usages.some((expected) => key.usages.includes(expected))) {
    let msg = "CryptoKey does not support this operation, its usages must include ";
    if (usages.length > 2) {
      const last = usages.pop();
      msg += `one of ${usages.join(", ")}, or ${last}.`;
    } else if (usages.length === 2) {
      msg += `one of ${usages[0]} or ${usages[1]}.`;
    } else {
      msg += `${usages[0]}.`;
    }
    throw new TypeError(msg);
  }
}
function checkSigCryptoKey(key, alg, ...usages) {
  switch (alg) {
    case "HS256":
    case "HS384":
    case "HS512": {
      if (!isAlgorithm(key.algorithm, "HMAC"))
        throw unusable("HMAC");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "RS256":
    case "RS384":
    case "RS512": {
      if (!isAlgorithm(key.algorithm, "RSASSA-PKCS1-v1_5"))
        throw unusable("RSASSA-PKCS1-v1_5");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "PS256":
    case "PS384":
    case "PS512": {
      if (!isAlgorithm(key.algorithm, "RSA-PSS"))
        throw unusable("RSA-PSS");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "EdDSA": {
      if (key.algorithm.name !== "Ed25519" && key.algorithm.name !== "Ed448") {
        throw unusable("Ed25519 or Ed448");
      }
      break;
    }
    case "Ed25519": {
      if (!isAlgorithm(key.algorithm, "Ed25519"))
        throw unusable("Ed25519");
      break;
    }
    case "ES256":
    case "ES384":
    case "ES512": {
      if (!isAlgorithm(key.algorithm, "ECDSA"))
        throw unusable("ECDSA");
      const expected = getNamedCurve(alg);
      const actual = key.algorithm.namedCurve;
      if (actual !== expected)
        throw unusable(expected, "algorithm.namedCurve");
      break;
    }
    default:
      throw new TypeError("CryptoKey does not support this operation");
  }
  checkUsage(key, usages);
}

// node_modules/jose/dist/node/esm/lib/invalid_key_input.js
function message(msg, actual, ...types4) {
  types4 = types4.filter(Boolean);
  if (types4.length > 2) {
    const last = types4.pop();
    msg += `one of type ${types4.join(", ")}, or ${last}.`;
  } else if (types4.length === 2) {
    msg += `one of type ${types4[0]} or ${types4[1]}.`;
  } else {
    msg += `of type ${types4[0]}.`;
  }
  if (actual == null) {
    msg += ` Received ${actual}`;
  } else if (typeof actual === "function" && actual.name) {
    msg += ` Received function ${actual.name}`;
  } else if (typeof actual === "object" && actual != null) {
    if (actual.constructor?.name) {
      msg += ` Received an instance of ${actual.constructor.name}`;
    }
  }
  return msg;
}
var invalid_key_input_default = (actual, ...types4) => {
  return message("Key must be ", actual, ...types4);
};
function withAlg(alg, actual, ...types4) {
  return message(`Key for the ${alg} algorithm must be `, actual, ...types4);
}

// node_modules/jose/dist/node/esm/runtime/is_key_like.js
var is_key_like_default = (key) => is_key_object_default(key) || isCryptoKey(key);
var types3 = ["KeyObject"];
if (globalThis.CryptoKey || webcrypto_default?.CryptoKey) {
  types3.push("CryptoKey");
}

// node_modules/jose/dist/node/esm/lib/is_disjoint.js
var isDisjoint = (...headers) => {
  const sources = headers.filter(Boolean);
  if (sources.length === 0 || sources.length === 1) {
    return true;
  }
  let acc;
  for (const header2 of sources) {
    const parameters = Object.keys(header2);
    if (!acc || acc.size === 0) {
      acc = new Set(parameters);
      continue;
    }
    for (const parameter of parameters) {
      if (acc.has(parameter)) {
        return false;
      }
      acc.add(parameter);
    }
  }
  return true;
};
var is_disjoint_default = isDisjoint;

// node_modules/jose/dist/node/esm/lib/is_object.js
function isObjectLike(value) {
  return typeof value === "object" && value !== null;
}
function isObject(input) {
  if (!isObjectLike(input) || Object.prototype.toString.call(input) !== "[object Object]") {
    return false;
  }
  if (Object.getPrototypeOf(input) === null) {
    return true;
  }
  let proto = input;
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto);
  }
  return Object.getPrototypeOf(input) === proto;
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
import { KeyObject } from "node:crypto";

// node_modules/jose/dist/node/esm/lib/is_jwk.js
function isJWK(key) {
  return isObject(key) && typeof key.kty === "string";
}
function isPrivateJWK(key) {
  return key.kty !== "oct" && typeof key.d === "string";
}
function isPublicJWK(key) {
  return key.kty !== "oct" && typeof key.d === "undefined";
}
function isSecretJWK(key) {
  return isJWK(key) && key.kty === "oct" && typeof key.k === "string";
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
var namedCurveToJOSE = (namedCurve) => {
  switch (namedCurve) {
    case "prime256v1":
      return "P-256";
    case "secp384r1":
      return "P-384";
    case "secp521r1":
      return "P-521";
    case "secp256k1":
      return "secp256k1";
    default:
      throw new JOSENotSupported("Unsupported key curve for this operation");
  }
};
var getNamedCurve2 = (kee, raw) => {
  let key;
  if (isCryptoKey(kee)) {
    key = KeyObject.from(kee);
  } else if (is_key_object_default(kee)) {
    key = kee;
  } else if (isJWK(kee)) {
    return kee.crv;
  } else {
    throw new TypeError(invalid_key_input_default(kee, ...types3));
  }
  if (key.type === "secret") {
    throw new TypeError('only "private" or "public" type keys can be used for this operation');
  }
  switch (key.asymmetricKeyType) {
    case "ed25519":
    case "ed448":
      return `Ed${key.asymmetricKeyType.slice(2)}`;
    case "x25519":
    case "x448":
      return `X${key.asymmetricKeyType.slice(1)}`;
    case "ec": {
      const namedCurve = key.asymmetricKeyDetails.namedCurve;
      if (raw) {
        return namedCurve;
      }
      return namedCurveToJOSE(namedCurve);
    }
    default:
      throw new TypeError("Invalid asymmetric key type for this operation");
  }
};
var get_named_curve_default = getNamedCurve2;

// node_modules/jose/dist/node/esm/runtime/check_key_length.js
import { KeyObject as KeyObject2 } from "node:crypto";
var check_key_length_default = (key, alg) => {
  let modulusLength;
  try {
    if (key instanceof KeyObject2) {
      modulusLength = key.asymmetricKeyDetails?.modulusLength;
    } else {
      modulusLength = Buffer.from(key.n, "base64url").byteLength << 3;
    }
  } catch {
  }
  if (typeof modulusLength !== "number" || modulusLength < 2048) {
    throw new TypeError(`${alg} requires key modulusLength to be 2048 bits or larger`);
  }
};

// node_modules/jose/dist/node/esm/runtime/asn1.js
import { createPrivateKey, createPublicKey, KeyObject as KeyObject3 } from "node:crypto";
import { Buffer as Buffer3 } from "node:buffer";
var fromSPKI = (pem2) => createPublicKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, ""), "base64"),
  type: "spki",
  format: "der"
});

// node_modules/jose/dist/node/esm/runtime/jwk_to_key.js
import { createPrivateKey as createPrivateKey2, createPublicKey as createPublicKey2 } from "node:crypto";
var parse = (key) => {
  if (key.d) {
    return createPrivateKey2({ format: "jwk", key });
  }
  return createPublicKey2({ format: "jwk", key });
};
var jwk_to_key_default = parse;

// node_modules/jose/dist/node/esm/key/import.js
async function importSPKI(spki, alg, options) {
  if (typeof spki !== "string" || spki.indexOf("-----BEGIN PUBLIC KEY-----") !== 0) {
    throw new TypeError('"spki" must be SPKI formatted string');
  }
  return fromSPKI(spki, alg, options);
}
async function importJWK(jwk, alg) {
  if (!isObject(jwk)) {
    throw new TypeError("JWK must be an object");
  }
  alg ||= jwk.alg;
  switch (jwk.kty) {
    case "oct":
      if (typeof jwk.k !== "string" || !jwk.k) {
        throw new TypeError('missing "k" (Key Value) Parameter value');
      }
      return decode(jwk.k);
    case "RSA":
      if ("oth" in jwk && jwk.oth !== void 0) {
        throw new JOSENotSupported('RSA JWK "oth" (Other Primes Info) Parameter value is not supported');
      }
    case "EC":
    case "OKP":
      return jwk_to_key_default({ ...jwk, alg });
    default:
      throw new JOSENotSupported('Unsupported "kty" (Key Type) Parameter value');
  }
}

// node_modules/jose/dist/node/esm/lib/check_key_type.js
var tag = (key) => key?.[Symbol.toStringTag];
var jwkMatchesOp = (alg, key, usage) => {
  if (key.use !== void 0 && key.use !== "sig") {
    throw new TypeError("Invalid key for this operation, when present its use must be sig");
  }
  if (key.key_ops !== void 0 && key.key_ops.includes?.(usage) !== true) {
    throw new TypeError(`Invalid key for this operation, when present its key_ops must include ${usage}`);
  }
  if (key.alg !== void 0 && key.alg !== alg) {
    throw new TypeError(`Invalid key for this operation, when present its alg must be ${alg}`);
  }
  return true;
};
var symmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (key instanceof Uint8Array)
    return;
  if (allowJwk && isJWK(key)) {
    if (isSecretJWK(key) && jwkMatchesOp(alg, key, usage))
      return;
    throw new TypeError(`JSON Web Key for symmetric algorithms must have JWK "kty" (Key Type) equal to "oct" and the JWK "k" (Key Value) present`);
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, "Uint8Array", allowJwk ? "JSON Web Key" : null));
  }
  if (key.type !== "secret") {
    throw new TypeError(`${tag(key)} instances for symmetric algorithms must be of type "secret"`);
  }
};
var asymmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (allowJwk && isJWK(key)) {
    switch (usage) {
      case "sign":
        if (isPrivateJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a private JWK`);
      case "verify":
        if (isPublicJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a public JWK`);
    }
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, allowJwk ? "JSON Web Key" : null));
  }
  if (key.type === "secret") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
  }
  if (usage === "sign" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm signing must be of type "private"`);
  }
  if (usage === "decrypt" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm decryption must be of type "private"`);
  }
  if (key.algorithm && usage === "verify" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm verifying must be of type "public"`);
  }
  if (key.algorithm && usage === "encrypt" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm encryption must be of type "public"`);
  }
};
function checkKeyType(allowJwk, alg, key, usage) {
  const symmetric = alg.startsWith("HS") || alg === "dir" || alg.startsWith("PBES2") || /^A\d{3}(?:GCM)?KW$/.test(alg);
  if (symmetric) {
    symmetricTypeCheck(alg, key, usage, allowJwk);
  } else {
    asymmetricTypeCheck(alg, key, usage, allowJwk);
  }
}
var check_key_type_default = checkKeyType.bind(void 0, false);
var checkKeyTypeWithJwk = checkKeyType.bind(void 0, true);

// node_modules/jose/dist/node/esm/lib/validate_crit.js
function validateCrit(Err, recognizedDefault, recognizedOption, protectedHeader, joseHeader) {
  if (joseHeader.crit !== void 0 && protectedHeader?.crit === void 0) {
    throw new Err('"crit" (Critical) Header Parameter MUST be integrity protected');
  }
  if (!protectedHeader || protectedHeader.crit === void 0) {
    return /* @__PURE__ */ new Set();
  }
  if (!Array.isArray(protectedHeader.crit) || protectedHeader.crit.length === 0 || protectedHeader.crit.some((input) => typeof input !== "string" || input.length === 0)) {
    throw new Err('"crit" (Critical) Header Parameter MUST be an array of non-empty strings when present');
  }
  let recognized;
  if (recognizedOption !== void 0) {
    recognized = new Map([...Object.entries(recognizedOption), ...recognizedDefault.entries()]);
  } else {
    recognized = recognizedDefault;
  }
  for (const parameter of protectedHeader.crit) {
    if (!recognized.has(parameter)) {
      throw new JOSENotSupported(`Extension Header Parameter "${parameter}" is not recognized`);
    }
    if (joseHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" is missing`);
    }
    if (recognized.get(parameter) && protectedHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" MUST be integrity protected`);
    }
  }
  return new Set(protectedHeader.crit);
}
var validate_crit_default = validateCrit;

// node_modules/jose/dist/node/esm/lib/validate_algorithms.js
var validateAlgorithms = (option, algorithms) => {
  if (algorithms !== void 0 && (!Array.isArray(algorithms) || algorithms.some((s) => typeof s !== "string"))) {
    throw new TypeError(`"${option}" option must be an array of strings`);
  }
  if (!algorithms) {
    return void 0;
  }
  return new Set(algorithms);
};
var validate_algorithms_default = validateAlgorithms;

// node_modules/jose/dist/node/esm/runtime/verify.js
import * as crypto3 from "node:crypto";
import { promisify as promisify2 } from "node:util";

// node_modules/jose/dist/node/esm/runtime/dsa_digest.js
function dsaDigest(alg) {
  switch (alg) {
    case "PS256":
    case "RS256":
    case "ES256":
    case "ES256K":
      return "sha256";
    case "PS384":
    case "RS384":
    case "ES384":
      return "sha384";
    case "PS512":
    case "RS512":
    case "ES512":
      return "sha512";
    case "Ed25519":
    case "EdDSA":
      return void 0;
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/node_key.js
import { constants, KeyObject as KeyObject4 } from "node:crypto";
var ecCurveAlgMap = /* @__PURE__ */ new Map([
  ["ES256", "P-256"],
  ["ES256K", "secp256k1"],
  ["ES384", "P-384"],
  ["ES512", "P-521"]
]);
function keyForCrypto(alg, key) {
  let asymmetricKeyType;
  let asymmetricKeyDetails;
  let isJWK2;
  if (key instanceof KeyObject4) {
    asymmetricKeyType = key.asymmetricKeyType;
    asymmetricKeyDetails = key.asymmetricKeyDetails;
  } else {
    isJWK2 = true;
    switch (key.kty) {
      case "RSA":
        asymmetricKeyType = "rsa";
        break;
      case "EC":
        asymmetricKeyType = "ec";
        break;
      case "OKP": {
        if (key.crv === "Ed25519") {
          asymmetricKeyType = "ed25519";
          break;
        }
        if (key.crv === "Ed448") {
          asymmetricKeyType = "ed448";
          break;
        }
        throw new TypeError("Invalid key for this operation, its crv must be Ed25519 or Ed448");
      }
      default:
        throw new TypeError("Invalid key for this operation, its kty must be RSA, OKP, or EC");
    }
  }
  let options;
  switch (alg) {
    case "Ed25519":
      if (asymmetricKeyType !== "ed25519") {
        throw new TypeError(`Invalid key for this operation, its asymmetricKeyType must be ed25519`);
      }
      break;
    case "EdDSA":
      if (!["ed25519", "ed448"].includes(asymmetricKeyType)) {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ed25519 or ed448");
      }
      break;
    case "RS256":
    case "RS384":
    case "RS512":
      if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa");
      }
      check_key_length_default(key, alg);
      break;
    case "PS256":
    case "PS384":
    case "PS512":
      if (asymmetricKeyType === "rsa-pss") {
        const { hashAlgorithm, mgf1HashAlgorithm, saltLength } = asymmetricKeyDetails;
        const length = parseInt(alg.slice(-3), 10);
        if (hashAlgorithm !== void 0 && (hashAlgorithm !== `sha${length}` || mgf1HashAlgorithm !== hashAlgorithm)) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameters do not meet the requirements of "alg" ${alg}`);
        }
        if (saltLength !== void 0 && saltLength > length >> 3) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameter saltLength does not meet the requirements of "alg" ${alg}`);
        }
      } else if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa or rsa-pss");
      }
      check_key_length_default(key, alg);
      options = {
        padding: constants.RSA_PKCS1_PSS_PADDING,
        saltLength: constants.RSA_PSS_SALTLEN_DIGEST
      };
      break;
    case "ES256":
    case "ES256K":
    case "ES384":
    case "ES512": {
      if (asymmetricKeyType !== "ec") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ec");
      }
      const actual = get_named_curve_default(key);
      const expected = ecCurveAlgMap.get(alg);
      if (actual !== expected) {
        throw new TypeError(`Invalid key curve for the algorithm, its curve must be ${expected}, got ${actual}`);
      }
      options = { dsaEncoding: "ieee-p1363" };
      break;
    }
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
  if (isJWK2) {
    return { format: "jwk", key, ...options };
  }
  return options ? { ...options, key } : key;
}

// node_modules/jose/dist/node/esm/runtime/sign.js
import * as crypto2 from "node:crypto";
import { promisify } from "node:util";

// node_modules/jose/dist/node/esm/runtime/hmac_digest.js
function hmacDigest(alg) {
  switch (alg) {
    case "HS256":
      return "sha256";
    case "HS384":
      return "sha384";
    case "HS512":
      return "sha512";
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/get_sign_verify_key.js
import { KeyObject as KeyObject5, createSecretKey } from "node:crypto";
function getSignVerifyKey(alg, key, usage) {
  if (key instanceof Uint8Array) {
    if (!alg.startsWith("HS")) {
      throw new TypeError(invalid_key_input_default(key, ...types3));
    }
    return createSecretKey(key);
  }
  if (key instanceof KeyObject5) {
    return key;
  }
  if (isCryptoKey(key)) {
    checkSigCryptoKey(key, alg, usage);
    return KeyObject5.from(key);
  }
  if (isJWK(key)) {
    if (alg.startsWith("HS")) {
      return createSecretKey(Buffer.from(key.k, "base64url"));
    }
    return key;
  }
  throw new TypeError(invalid_key_input_default(key, ...types3, "Uint8Array", "JSON Web Key"));
}

// node_modules/jose/dist/node/esm/runtime/sign.js
var oneShotSign = promisify(crypto2.sign);
var sign2 = async (alg, key, data) => {
  const k = getSignVerifyKey(alg, key, "sign");
  if (alg.startsWith("HS")) {
    const hmac = crypto2.createHmac(hmacDigest(alg), k);
    hmac.update(data);
    return hmac.digest();
  }
  return oneShotSign(dsaDigest(alg), data, keyForCrypto(alg, k));
};
var sign_default = sign2;

// node_modules/jose/dist/node/esm/runtime/verify.js
var oneShotVerify = promisify2(crypto3.verify);
var verify2 = async (alg, key, signature, data) => {
  const k = getSignVerifyKey(alg, key, "verify");
  if (alg.startsWith("HS")) {
    const expected = await sign_default(alg, k, data);
    const actual = signature;
    try {
      return crypto3.timingSafeEqual(actual, expected);
    } catch {
      return false;
    }
  }
  const algorithm = dsaDigest(alg);
  const keyInput = keyForCrypto(alg, k);
  try {
    return await oneShotVerify(algorithm, data, keyInput, signature);
  } catch {
    return false;
  }
};
var verify_default = verify2;

// node_modules/jose/dist/node/esm/jws/flattened/verify.js
async function flattenedVerify(jws, key, options) {
  if (!isObject(jws)) {
    throw new JWSInvalid("Flattened JWS must be an object");
  }
  if (jws.protected === void 0 && jws.header === void 0) {
    throw new JWSInvalid('Flattened JWS must have either of the "protected" or "header" members');
  }
  if (jws.protected !== void 0 && typeof jws.protected !== "string") {
    throw new JWSInvalid("JWS Protected Header incorrect type");
  }
  if (jws.payload === void 0) {
    throw new JWSInvalid("JWS Payload missing");
  }
  if (typeof jws.signature !== "string") {
    throw new JWSInvalid("JWS Signature missing or incorrect type");
  }
  if (jws.header !== void 0 && !isObject(jws.header)) {
    throw new JWSInvalid("JWS Unprotected Header incorrect type");
  }
  let parsedProt = {};
  if (jws.protected) {
    try {
      const protectedHeader = decode(jws.protected);
      parsedProt = JSON.parse(decoder.decode(protectedHeader));
    } catch {
      throw new JWSInvalid("JWS Protected Header is invalid");
    }
  }
  if (!is_disjoint_default(parsedProt, jws.header)) {
    throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
  }
  const joseHeader = {
    ...parsedProt,
    ...jws.header
  };
  const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, parsedProt, joseHeader);
  let b64 = true;
  if (extensions.has("b64")) {
    b64 = parsedProt.b64;
    if (typeof b64 !== "boolean") {
      throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
    }
  }
  const { alg } = joseHeader;
  if (typeof alg !== "string" || !alg) {
    throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
  }
  const algorithms = options && validate_algorithms_default("algorithms", options.algorithms);
  if (algorithms && !algorithms.has(alg)) {
    throw new JOSEAlgNotAllowed('"alg" (Algorithm) Header Parameter value not allowed');
  }
  if (b64) {
    if (typeof jws.payload !== "string") {
      throw new JWSInvalid("JWS Payload must be a string");
    }
  } else if (typeof jws.payload !== "string" && !(jws.payload instanceof Uint8Array)) {
    throw new JWSInvalid("JWS Payload must be a string or an Uint8Array instance");
  }
  let resolvedKey = false;
  if (typeof key === "function") {
    key = await key(parsedProt, jws);
    resolvedKey = true;
    checkKeyTypeWithJwk(alg, key, "verify");
    if (isJWK(key)) {
      key = await importJWK(key, alg);
    }
  } else {
    checkKeyTypeWithJwk(alg, key, "verify");
  }
  const data = concat(encoder.encode(jws.protected ?? ""), encoder.encode("."), typeof jws.payload === "string" ? encoder.encode(jws.payload) : jws.payload);
  let signature;
  try {
    signature = decode(jws.signature);
  } catch {
    throw new JWSInvalid("Failed to base64url decode the signature");
  }
  const verified = await verify_default(alg, key, signature, data);
  if (!verified) {
    throw new JWSSignatureVerificationFailed();
  }
  let payload;
  if (b64) {
    try {
      payload = decode(jws.payload);
    } catch {
      throw new JWSInvalid("Failed to base64url decode the payload");
    }
  } else if (typeof jws.payload === "string") {
    payload = encoder.encode(jws.payload);
  } else {
    payload = jws.payload;
  }
  const result = { payload };
  if (jws.protected !== void 0) {
    result.protectedHeader = parsedProt;
  }
  if (jws.header !== void 0) {
    result.unprotectedHeader = jws.header;
  }
  if (resolvedKey) {
    return { ...result, key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/compact/verify.js
async function compactVerify(jws, key, options) {
  if (jws instanceof Uint8Array) {
    jws = decoder.decode(jws);
  }
  if (typeof jws !== "string") {
    throw new JWSInvalid("Compact JWS must be a string or Uint8Array");
  }
  const { 0: protectedHeader, 1: payload, 2: signature, length } = jws.split(".");
  if (length !== 3) {
    throw new JWSInvalid("Invalid Compact JWS");
  }
  const verified = await flattenedVerify({ payload, protected: protectedHeader, signature }, key, options);
  const result = { payload: verified.payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/lib/epoch.js
var epoch_default = (date) => Math.floor(date.getTime() / 1e3);

// node_modules/jose/dist/node/esm/lib/secs.js
var minute = 60;
var hour = minute * 60;
var day = hour * 24;
var week = day * 7;
var year = day * 365.25;
var REGEX = /^(\+|\-)? ?(\d+|\d+\.\d+) ?(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)(?: (ago|from now))?$/i;
var secs_default = (str) => {
  const matched = REGEX.exec(str);
  if (!matched || matched[4] && matched[1]) {
    throw new TypeError("Invalid time period format");
  }
  const value = parseFloat(matched[2]);
  const unit = matched[3].toLowerCase();
  let numericDate;
  switch (unit) {
    case "sec":
    case "secs":
    case "second":
    case "seconds":
    case "s":
      numericDate = Math.round(value);
      break;
    case "minute":
    case "minutes":
    case "min":
    case "mins":
    case "m":
      numericDate = Math.round(value * minute);
      break;
    case "hour":
    case "hours":
    case "hr":
    case "hrs":
    case "h":
      numericDate = Math.round(value * hour);
      break;
    case "day":
    case "days":
    case "d":
      numericDate = Math.round(value * day);
      break;
    case "week":
    case "weeks":
    case "w":
      numericDate = Math.round(value * week);
      break;
    default:
      numericDate = Math.round(value * year);
      break;
  }
  if (matched[1] === "-" || matched[4] === "ago") {
    return -numericDate;
  }
  return numericDate;
};

// node_modules/jose/dist/node/esm/lib/jwt_claims_set.js
var normalizeTyp = (value) => value.toLowerCase().replace(/^application\//, "");
var checkAudiencePresence = (audPayload, audOption) => {
  if (typeof audPayload === "string") {
    return audOption.includes(audPayload);
  }
  if (Array.isArray(audPayload)) {
    return audOption.some(Set.prototype.has.bind(new Set(audPayload)));
  }
  return false;
};
var jwt_claims_set_default = (protectedHeader, encodedPayload, options = {}) => {
  let payload;
  try {
    payload = JSON.parse(decoder.decode(encodedPayload));
  } catch {
  }
  if (!isObject(payload)) {
    throw new JWTInvalid("JWT Claims Set must be a top-level JSON object");
  }
  const { typ } = options;
  if (typ && (typeof protectedHeader.typ !== "string" || normalizeTyp(protectedHeader.typ) !== normalizeTyp(typ))) {
    throw new JWTClaimValidationFailed('unexpected "typ" JWT header value', payload, "typ", "check_failed");
  }
  const { requiredClaims = [], issuer, subject, audience, maxTokenAge } = options;
  const presenceCheck = [...requiredClaims];
  if (maxTokenAge !== void 0)
    presenceCheck.push("iat");
  if (audience !== void 0)
    presenceCheck.push("aud");
  if (subject !== void 0)
    presenceCheck.push("sub");
  if (issuer !== void 0)
    presenceCheck.push("iss");
  for (const claim of new Set(presenceCheck.reverse())) {
    if (!(claim in payload)) {
      throw new JWTClaimValidationFailed(`missing required "${claim}" claim`, payload, claim, "missing");
    }
  }
  if (issuer && !(Array.isArray(issuer) ? issuer : [issuer]).includes(payload.iss)) {
    throw new JWTClaimValidationFailed('unexpected "iss" claim value', payload, "iss", "check_failed");
  }
  if (subject && payload.sub !== subject) {
    throw new JWTClaimValidationFailed('unexpected "sub" claim value', payload, "sub", "check_failed");
  }
  if (audience && !checkAudiencePresence(payload.aud, typeof audience === "string" ? [audience] : audience)) {
    throw new JWTClaimValidationFailed('unexpected "aud" claim value', payload, "aud", "check_failed");
  }
  let tolerance;
  switch (typeof options.clockTolerance) {
    case "string":
      tolerance = secs_default(options.clockTolerance);
      break;
    case "number":
      tolerance = options.clockTolerance;
      break;
    case "undefined":
      tolerance = 0;
      break;
    default:
      throw new TypeError("Invalid clockTolerance option type");
  }
  const { currentDate } = options;
  const now = epoch_default(currentDate || /* @__PURE__ */ new Date());
  if ((payload.iat !== void 0 || maxTokenAge) && typeof payload.iat !== "number") {
    throw new JWTClaimValidationFailed('"iat" claim must be a number', payload, "iat", "invalid");
  }
  if (payload.nbf !== void 0) {
    if (typeof payload.nbf !== "number") {
      throw new JWTClaimValidationFailed('"nbf" claim must be a number', payload, "nbf", "invalid");
    }
    if (payload.nbf > now + tolerance) {
      throw new JWTClaimValidationFailed('"nbf" claim timestamp check failed', payload, "nbf", "check_failed");
    }
  }
  if (payload.exp !== void 0) {
    if (typeof payload.exp !== "number") {
      throw new JWTClaimValidationFailed('"exp" claim must be a number', payload, "exp", "invalid");
    }
    if (payload.exp <= now - tolerance) {
      throw new JWTExpired('"exp" claim timestamp check failed', payload, "exp", "check_failed");
    }
  }
  if (maxTokenAge) {
    const age = now - payload.iat;
    const max = typeof maxTokenAge === "number" ? maxTokenAge : secs_default(maxTokenAge);
    if (age - tolerance > max) {
      throw new JWTExpired('"iat" claim timestamp check failed (too far in the past)', payload, "iat", "check_failed");
    }
    if (age < 0 - tolerance) {
      throw new JWTClaimValidationFailed('"iat" claim timestamp check failed (it should be in the past)', payload, "iat", "check_failed");
    }
  }
  return payload;
};

// node_modules/jose/dist/node/esm/jwt/verify.js
async function jwtVerify(jwt, key, options) {
  const verified = await compactVerify(jwt, key, options);
  if (verified.protectedHeader.crit?.includes("b64") && verified.protectedHeader.b64 === false) {
    throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
  }
  const payload = jwt_claims_set_default(verified.protectedHeader, verified.payload, options);
  const result = { payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// packages/server-core/src/jwt.ts
var ALG = "EdDSA";
var ISSUER = "shikhon-lms";
function pem(envVar) {
  const v = process.env[envVar];
  if (!v) throw new Error(`${envVar} env var is not set`);
  return v.includes("\\n") ? v.replace(/\\n/g, "\n") : v;
}
var _publicKey = null;
function publicKey() {
  if (!_publicKey) _publicKey = importSPKI(pem("JWT_PUBLIC_KEY"), ALG);
  return _publicKey;
}
async function verifyAccessToken(token) {
  const key = await publicKey();
  const { payload } = await jwtVerify(token, key, { issuer: ISSUER });
  if (!payload.sub || !payload.tid || !payload.role) {
    throw new Error("access token missing required claims");
  }
  return {
    sub: payload.sub,
    tid: payload.tid,
    role: payload.role,
    roles: payload.roles ?? [payload.role]
  };
}

// packages/server-core/src/auth.ts
async function authenticate(req) {
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) throw new HttpError(401, "missing bearer token", "unauthorized");
  try {
    return await verifyAccessToken(token);
  } catch {
    throw new HttpError(401, "invalid or expired access token", "unauthorized");
  }
}
var STAFF_BLOCKLIST = /* @__PURE__ */ new Set(["student", "guardian"]);
function requireStaff(claims) {
  if (STAFF_BLOCKLIST.has(claims.role)) {
    throw new HttpError(403, "this endpoint is restricted to staff", "forbidden");
  }
}
function requireRole(claims, allowed) {
  if (!allowed.includes(claims.role)) {
    throw new HttpError(403, `this endpoint requires one of: ${allowed.join(", ")}`, "forbidden");
  }
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// packages/server-core/src/audit.ts
async function writeAudit(client, actor, entry) {
  const sp = `audit_${Math.random().toString(36).slice(2, 10)}`;
  try {
    await client.query(`SAVEPOINT ${sp}`);
  } catch {
  }
  try {
    await client.query(
      `INSERT INTO audit.activity_log
         (tenant_id, actor_id, actor_role, action, entity_type, entity_id,
          before_state, after_state)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8::jsonb)`,
      [
        actor.tenantId,
        actor.userId,
        actor.role,
        entry.action,
        entry.entityType,
        entry.entityId ?? null,
        entry.before === void 0 ? null : JSON.stringify(entry.before),
        entry.after === void 0 ? null : JSON.stringify(entry.after)
      ]
    );
    try {
      await client.query(`RELEASE SAVEPOINT ${sp}`);
    } catch {
    }
  } catch {
    try {
      await client.query(`ROLLBACK TO SAVEPOINT ${sp}`);
    } catch {
    }
  }
}

// services/finance-svc/api/feestructures.ts
var SERVICE = "finance";
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var FEE_ADMIN_ROLES = ["principal", "school_owner", "accountant", "it_admin"];
var AMOUNT_MAX = 1e7;
var DUE_DAY_MIN = 1;
var DUE_DAY_MAX = 28;
var DUE_DAY_MIN_BN = "\u09E7";
var DUE_DAY_MAX_BN = "\u09E8\u09EE";
async function handler(req, res, cors) {
  const claims = await authenticate(req);
  const db = await sharedDb();
  const ctx = {
    tenantId: claims.tid,
    userId: claims.sub,
    role: claims.role,
    service: SERVICE
  };
  if (req.method === "GET") {
    requireStaff(claims);
    json(res, 200, await list(db, ctx, req, claims.role), cors);
    return;
  }
  if (req.method === "POST") {
    requireRole(claims, FEE_ADMIN_ROLES);
    json(res, 200, await create(db, ctx, req), cors);
    return;
  }
  if (req.method === "PATCH") {
    requireRole(claims, FEE_ADMIN_ROLES);
    json(res, 200, await update(db, ctx, req), cors);
    return;
  }
  if (req.method === "DELETE") {
    requireRole(claims, FEE_ADMIN_ROLES);
    json(res, 200, await remove(db, ctx, req), cors);
    return;
  }
  json(res, 405, { error: "method_not_allowed" }, cors);
}
var shape = (r) => ({
  id: r.id,
  feeHeadId: r.fee_head_id,
  headBn: r.head_bn,
  headCode: r.head_code,
  frequency: r.frequency,
  headActive: r.head_active,
  academicYearId: r.academic_year_id,
  classId: r.class_id,
  classBn: r.class_bn,
  amount: Number(r.amount),
  lateFeePerDay: r.late_fee_per_day === null ? null : Number(r.late_fee_per_day),
  lateFeeCap: r.late_fee_cap === null ? null : Number(r.late_fee_cap),
  dueDayOfMonth: r.due_day_of_month,
  // The honest flag. A price on a non-monthly head is stored and never
  // invoiced by the monthly run, and the office deserves to be told on the
  // row rather than left to wonder.
  billedByMonthlyRun: r.frequency === "monthly" && r.head_active
});
async function list(db, ctx, req, role) {
  const yearId = query(req).get("yearId") ?? "";
  if (yearId && !UUID_RE.test(yearId)) {
    throw new HttpError(400, "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09AC\u09B0\u09CD\u09B7 \u09B8\u09A0\u09BF\u0995 \u09A8\u09AF\u09BC\u0964", "bad_year", { field: "yearId" });
  }
  return db.withTenant(ctx, async (c) => {
    const year2 = yearId || (await c.query(
      `SELECT id FROM academic_years WHERE is_current ORDER BY starts_on DESC LIMIT 1`
    )).rows[0]?.id || "";
    if (!year2) {
      return {
        canManage: FEE_ADMIN_ROLES.includes(role),
        academicYearId: null,
        years: [],
        classes: [],
        heads: [],
        structures: []
      };
    }
    const [structures, years, classes, heads] = await Promise.all([
      c.query(
        `SELECT fs.id, fs.fee_head_id, fh.name_bn AS head_bn, fh.code AS head_code,
                fh.frequency, fh.is_active AS head_active,
                fs.academic_year_id, fs.class_id, cl.name_bn AS class_bn,
                fs.amount, fs.late_fee_per_day, fs.late_fee_cap, fs.due_day_of_month
           FROM fee_structures fs
           JOIN fee_heads fh ON fh.id = fs.fee_head_id
           LEFT JOIN classes cl ON cl.id = fs.class_id
          WHERE fs.academic_year_id = $1
          ORDER BY fh.frequency, fh.name_bn, cl.level_no NULLS FIRST`,
        [year2]
      ),
      c.query(
        `SELECT id, label, is_current FROM academic_years ORDER BY starts_on DESC`
      ),
      c.query(
        `SELECT id, name_bn FROM classes ORDER BY level_no, name_bn`
      ),
      c.query(
        `SELECT id, name_bn, code, frequency, is_active FROM fee_heads
          ORDER BY is_active DESC, frequency, name_bn`
      )
    ]);
    return {
      canManage: FEE_ADMIN_ROLES.includes(role),
      academicYearId: year2,
      years: years.rows.map((y) => ({ id: y.id, label: y.label, isCurrent: y.is_current })),
      classes: classes.rows.map((x) => ({ id: x.id, nameBn: x.name_bn })),
      heads: heads.rows.map((h) => ({
        id: h.id,
        nameBn: h.name_bn,
        code: h.code,
        frequency: h.frequency,
        isActive: h.is_active
      })),
      structures: structures.rows.map(shape)
    };
  });
}
function money(v, field, label) {
  if (v === void 0 || v === null || v === "") return null;
  const n = Number(v);
  if (!Number.isFinite(n) || n < 0) {
    throw new HttpError(400, `${label} \u098B\u09A3\u09BE\u09A4\u09CD\u09AE\u0995 \u09B9\u09A4\u09C7 \u09AA\u09BE\u09B0\u09C7 \u09A8\u09BE\u0964`, "bad_amount", { field });
  }
  if (n > AMOUNT_MAX) {
    throw new HttpError(400, `${label} \u0985\u09A8\u09C7\u0995 \u09AC\u09C7\u09B6\u09BF \u2014 \u0986\u09AC\u09BE\u09B0 \u09A6\u09C7\u0996\u09C1\u09A8\u0964`, "bad_amount", { field });
  }
  return Math.round(n * 100) / 100;
}
function validate(b) {
  const amount = money(b.amount, "amount", "\u099F\u09BE\u0995\u09BE\u09B0 \u0985\u0999\u09CD\u0995");
  if (amount === null) {
    throw new HttpError(400, "\u099F\u09BE\u0995\u09BE\u09B0 \u0985\u0999\u09CD\u0995 \u09B2\u09BF\u0996\u09C1\u09A8\u0964", "bad_amount", { field: "amount" });
  }
  const lateFeePerDay = money(b.lateFeePerDay, "lateFeePerDay", "\u09A6\u09C8\u09A8\u09BF\u0995 \u09AC\u09BF\u09B2\u09AE\u09CD\u09AC \u09AB\u09BF") ?? 0;
  const lateFeeCap = money(b.lateFeeCap, "lateFeeCap", "\u09AC\u09BF\u09B2\u09AE\u09CD\u09AC \u09AB\u09BF\u09B0 \u09B8\u09B0\u09CD\u09AC\u09CB\u099A\u09CD\u099A \u09B8\u09C0\u09AE\u09BE");
  let dueDay = null;
  if (b.dueDayOfMonth !== void 0 && b.dueDayOfMonth !== null) {
    dueDay = Number(b.dueDayOfMonth);
    if (!Number.isInteger(dueDay) || dueDay < DUE_DAY_MIN || dueDay > DUE_DAY_MAX) {
      throw new HttpError(
        400,
        `\u09B6\u09C7\u09B7 \u09A4\u09BE\u09B0\u09BF\u0996 ${DUE_DAY_MIN_BN} \u09A5\u09C7\u0995\u09C7 ${DUE_DAY_MAX_BN}-\u098F\u09B0 \u09AE\u09A7\u09CD\u09AF\u09C7 \u09A6\u09BF\u09A8\u0964`,
        "bad_due_day",
        { field: "dueDayOfMonth" }
      );
    }
  }
  return { amount, lateFeePerDay, lateFeeCap, dueDay };
}
async function create(db, ctx, req) {
  const body = await readJson(req);
  if (!UUID_RE.test(body.feeHeadId ?? "")) {
    throw new HttpError(400, "\u0995\u09CB\u09A8 \u09AB\u09BF \u09A4\u09BE \u09AC\u09C7\u099B\u09C7 \u09A8\u09BF\u09A8\u0964", "bad_head", { field: "feeHeadId" });
  }
  if (!UUID_RE.test(body.academicYearId ?? "")) {
    throw new HttpError(400, "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09AC\u09B0\u09CD\u09B7 \u09AC\u09C7\u099B\u09C7 \u09A8\u09BF\u09A8\u0964", "bad_year", { field: "academicYearId" });
  }
  const classId = body.classId ? String(body.classId) : null;
  if (classId !== null && !UUID_RE.test(classId)) {
    throw new HttpError(400, "\u09B6\u09CD\u09B0\u09C7\u09A3\u09BF \u09B8\u09A0\u09BF\u0995 \u09A8\u09AF\u09BC\u0964", "bad_class", { field: "classId" });
  }
  const v = validate(body);
  return db.withTenant(ctx, async (c) => {
    const head = await c.query(
      `SELECT name_bn, frequency FROM fee_heads WHERE id = $1`,
      [body.feeHeadId]
    );
    if (head.rowCount === 0) throw new HttpError(404, "\u09AB\u09BF-\u098F\u09B0 \u0996\u09BE\u09A4\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "head_not_found");
    const yr = await c.query(`SELECT 1 FROM academic_years WHERE id = $1`, [body.academicYearId]);
    if (yr.rowCount === 0) throw new HttpError(404, "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09AC\u09B0\u09CD\u09B7\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "year_not_found");
    if (classId) {
      const cl = await c.query(`SELECT 1 FROM classes WHERE id = $1`, [classId]);
      if (cl.rowCount === 0) throw new HttpError(404, "\u09B6\u09CD\u09B0\u09C7\u09A3\u09BF\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "class_not_found");
    }
    const { rows } = await c.query(
      `INSERT INTO fee_structures
         (tenant_id, fee_head_id, academic_year_id, class_id, quota_category,
          amount, late_fee_per_day, late_fee_cap, due_day_of_month)
       VALUES (app.current_tenant(), $1, $2, $3, NULL, $4, $5, $6, $7)
       RETURNING id, fee_head_id, academic_year_id, class_id, amount,
                 late_fee_per_day, late_fee_cap, due_day_of_month,
                 '' AS head_bn, '' AS head_code, '' AS frequency,
                 true AS head_active, NULL AS class_bn`,
      [
        body.feeHeadId,
        body.academicYearId,
        classId,
        v.amount,
        v.lateFeePerDay,
        v.lateFeeCap,
        v.dueDay
      ]
    );
    await writeAudit(c, ctx, {
      action: "finance.fee_structure.create",
      entityType: "fee_structure",
      entityId: rows[0].id,
      after: {
        head: head.rows[0].name_bn,
        frequency: head.rows[0].frequency,
        classId,
        amount: v.amount,
        dueDayOfMonth: v.dueDay,
        lateFeePerDay: v.lateFeePerDay,
        lateFeeCap: v.lateFeeCap
      }
    });
    return { id: rows[0].id, headBn: head.rows[0].name_bn, amount: v.amount };
  }, { write: true });
}
async function update(db, ctx, req) {
  const body = await readJson(req);
  const id = (body.id ?? "").trim();
  if (!UUID_RE.test(id)) {
    throw new HttpError(400, "\u0995\u09CB\u09A8 \u09AB\u09BF \u09A4\u09BE \u099C\u09BE\u09A8\u09BE\u09A8\u09CB \u09B9\u09AF\u09BC\u09A8\u09BF\u0964", "structure_required", { field: "id" });
  }
  return db.withTenant(ctx, async (c) => {
    const before = await c.query(
      `SELECT fs.amount, fs.late_fee_per_day, fs.late_fee_cap, fs.due_day_of_month,
              fh.name_bn AS head_bn
         FROM fee_structures fs JOIN fee_heads fh ON fh.id = fs.fee_head_id
        WHERE fs.id = $1`,
      [id]
    );
    if (before.rowCount === 0) {
      throw new HttpError(404, "\u098F\u0987 \u09AB\u09BF-\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "structure_not_found");
    }
    const was = before.rows[0];
    const v = validate({
      amount: body.amount ?? Number(was.amount),
      lateFeePerDay: body.lateFeePerDay !== void 0 ? body.lateFeePerDay : was.late_fee_per_day === null ? null : Number(was.late_fee_per_day),
      lateFeeCap: body.lateFeeCap !== void 0 ? body.lateFeeCap : was.late_fee_cap === null ? null : Number(was.late_fee_cap),
      dueDayOfMonth: body.dueDayOfMonth !== void 0 ? body.dueDayOfMonth : was.due_day_of_month
    });
    await c.query(
      `UPDATE fee_structures
          SET amount = $2, late_fee_per_day = $3, late_fee_cap = $4, due_day_of_month = $5
        WHERE id = $1`,
      [id, v.amount, v.lateFeePerDay, v.lateFeeCap, v.dueDay]
    );
    await writeAudit(c, ctx, {
      action: "finance.fee_structure.update",
      entityType: "fee_structure",
      entityId: id,
      before: {
        head: was.head_bn,
        amount: Number(was.amount),
        dueDayOfMonth: was.due_day_of_month,
        lateFeePerDay: was.late_fee_per_day === null ? null : Number(was.late_fee_per_day)
      },
      after: {
        head: was.head_bn,
        amount: v.amount,
        dueDayOfMonth: v.dueDay,
        lateFeePerDay: v.lateFeePerDay
      }
    });
    return { id, headBn: was.head_bn, amount: v.amount };
  }, { write: true });
}
async function remove(db, ctx, req) {
  const id = query(req).get("id") ?? "";
  if (!UUID_RE.test(id)) {
    throw new HttpError(400, "\u0995\u09CB\u09A8 \u09AB\u09BF \u09A4\u09BE \u099C\u09BE\u09A8\u09BE\u09A8\u09CB \u09B9\u09AF\u09BC\u09A8\u09BF\u0964", "structure_required", { field: "id" });
  }
  return db.withTenant(ctx, async (c) => {
    const before = await c.query(
      `SELECT fs.amount, fs.class_id, fh.name_bn AS head_bn
         FROM fee_structures fs JOIN fee_heads fh ON fh.id = fs.fee_head_id
        WHERE fs.id = $1`,
      [id]
    );
    if (before.rowCount === 0) {
      throw new HttpError(404, "\u098F\u0987 \u09AB\u09BF-\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "structure_not_found");
    }
    const was = before.rows[0];
    const del = await c.query(`DELETE FROM fee_structures WHERE id = $1`, [id]);
    if (del.rowCount === 0) {
      throw new HttpError(403, "\u098F\u0987 \u09AB\u09BF \u09AE\u09C1\u099B\u09C7 \u09AB\u09C7\u09B2\u09BE\u09B0 \u0985\u09A8\u09C1\u09AE\u09A4\u09BF \u09A8\u09C7\u0987\u0964", "forbidden");
    }
    await writeAudit(c, ctx, {
      action: "finance.fee_structure.delete",
      entityType: "fee_structure",
      entityId: id,
      before: { head: was.head_bn, amount: Number(was.amount), classId: was.class_id }
    });
    return { id, headBn: was.head_bn, issuedInvoicesUnaffected: true };
  }, { write: true });
}

// services/finance-svc/api/payments.ts
var SERVICE2 = "finance";
var UUID_RE2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var COLLECT_ROLES = ["principal", "school_owner", "accountant"];
var METHODS = ["cash", "cheque", "bank_transfer", "bkash", "nagad", "rocket", "upay"];
var METHOD_BN = {
  cash: "\u09A8\u0997\u09A6",
  cheque: "\u099A\u09C7\u0995",
  bank_transfer: "\u09AC\u09CD\u09AF\u09BE\u0982\u0995 \u099F\u09CD\u09B0\u09BE\u09A8\u09CD\u09B8\u09AB\u09BE\u09B0",
  bkash: "\u09AC\u09BF\u0995\u09BE\u09B6",
  nagad: "\u09A8\u0997\u09A6 (Nagad)",
  rocket: "\u09B0\u0995\u09C7\u099F",
  upay: "\u0989\u09AA\u09BE\u09AF\u09BC"
};
var ACCOUNT_FOR = {
  cash: "CASH",
  cheque: "CASH",
  bank_transfer: "CASH",
  bkash: "MFS-BKASH",
  nagad: "MFS-NAGAD",
  rocket: "MFS-ROCKET",
  upay: "CASH"
};
async function handler2(req, res, cors) {
  const claims = await authenticate(req);
  const db = await sharedDb();
  const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role, service: SERVICE2 };
  if (req.method === "GET") {
    requireRole(claims, COLLECT_ROLES);
    json(res, 200, await list2(db, ctx, req), cors);
    return;
  }
  if (req.method === "POST") {
    requireRole(claims, COLLECT_ROLES);
    json(res, 200, await record(db, ctx, req), cors);
    return;
  }
  json(res, 405, { error: "method_not_allowed" }, cors);
}
async function list2(db, ctx, req) {
  const invoiceId = query(req).get("invoiceId") ?? "";
  if (!UUID_RE2.test(invoiceId)) {
    throw new HttpError(400, "\u0995\u09CB\u09A8 \u09AC\u09BF\u09B2 \u09A4\u09BE \u099C\u09BE\u09A8\u09BE\u09A8\u09CB \u09B9\u09AF\u09BC\u09A8\u09BF\u0964", "invoice_required", { field: "invoiceId" });
  }
  return db.withTenant(ctx, async (c) => {
    const inv = await c.query(
      `SELECT i.id, i.invoice_no, i.student_id, u.full_name_bn AS student_bn,
              i.billing_period, i.total_amount, i.paid_amount, i.balance_amount,
              i.status::text AS status, i.due_on
         FROM invoices i
         -- invoices.student_id is a FK to users(id) directly; there is no
         -- separate students table in this schema.
         JOIN users u ON u.id = i.student_id
        WHERE i.id = $1`,
      [invoiceId]
    );
    if (inv.rowCount === 0) {
      throw new HttpError(404, "\u09AC\u09BF\u09B2\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "invoice_not_found");
    }
    const i = inv.rows[0];
    const receipts2 = await c.query(
      `SELECT r.id, r.receipt_no, r.amount, r.method::text AS method, r.issued_at,
              u.full_name_bn AS issued_by_bn
         FROM payment_receipts r
         LEFT JOIN users u ON u.id = r.issued_by
        WHERE r.invoice_id = $1
        ORDER BY r.issued_at`,
      [invoiceId]
    );
    return {
      canCollect: COLLECT_ROLES.includes(ctx.role),
      methods: METHODS.map((m) => ({ code: m, labelBn: METHOD_BN[m] ?? m })),
      invoice: {
        id: i.id,
        invoiceNo: i.invoice_no,
        studentId: i.student_id,
        studentBn: i.student_bn,
        billingPeriod: i.billing_period,
        totalAmount: Number(i.total_amount),
        paidAmount: Number(i.paid_amount),
        balanceAmount: Number(i.balance_amount),
        status: i.status,
        dueOn: i.due_on
      },
      receipts: receipts2.rows.map((r) => ({
        id: r.id,
        receiptNo: r.receipt_no,
        amount: Number(r.amount),
        method: r.method,
        methodBn: METHOD_BN[r.method] ?? r.method,
        issuedAt: r.issued_at,
        issuedByBn: r.issued_by_bn
      }))
    };
  });
}
async function record(db, ctx, req) {
  const b = await readJson(req);
  const invoiceId = (b.invoiceId ?? "").trim();
  if (!UUID_RE2.test(invoiceId)) {
    throw new HttpError(400, "\u0995\u09CB\u09A8 \u09AC\u09BF\u09B2 \u09A4\u09BE \u099C\u09BE\u09A8\u09BE\u09A8\u09CB \u09B9\u09AF\u09BC\u09A8\u09BF\u0964", "invoice_required", { field: "invoiceId" });
  }
  const method = (b.method ?? "").trim();
  if (!METHODS.includes(method)) {
    throw new HttpError(400, "\u0995\u09C0\u09AD\u09BE\u09AC\u09C7 \u099F\u09BE\u0995\u09BE \u098F\u09B8\u09C7\u099B\u09C7 \u09A4\u09BE \u09AC\u09C7\u099B\u09C7 \u09A8\u09BF\u09A8\u0964", "bad_method", { field: "method" });
  }
  const amount = Number(b.amount);
  if (!Number.isFinite(amount) || amount <= 0) {
    throw new HttpError(400, "\u099F\u09BE\u0995\u09BE\u09B0 \u0985\u0999\u09CD\u0995 \u09B6\u09C2\u09A8\u09CD\u09AF\u09C7\u09B0 \u09AC\u09C7\u09B6\u09BF \u09B9\u09A4\u09C7 \u09B9\u09AC\u09C7\u0964", "bad_amount", { field: "amount" });
  }
  const paid = Math.round(amount * 100) / 100;
  const reference = (b.reference ?? "").trim().slice(0, 120);
  return db.withTenant(ctx, async (c) => {
    const inv = await c.query(
      `SELECT student_id, invoice_no, balance_amount, status::text AS status
         FROM invoices WHERE id = $1`,
      [invoiceId]
    );
    if (inv.rowCount === 0) {
      throw new HttpError(404, "\u09AC\u09BF\u09B2\u099F\u09BF \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964", "invoice_not_found");
    }
    const invoice = inv.rows[0];
    if (invoice.status === "cancelled") {
      throw new HttpError(409, "\u09AC\u09BE\u09A4\u09BF\u09B2 \u0995\u09B0\u09BE \u09AC\u09BF\u09B2\u09C7 \u099F\u09BE\u0995\u09BE \u09A8\u09C7\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC \u09A8\u09BE\u0964", "invoice_cancelled");
    }
    if (invoice.status === "draft") {
      throw new HttpError(409, "\u0996\u09B8\u09A1\u09BC\u09BE \u09AC\u09BF\u09B2\u09C7 \u099F\u09BE\u0995\u09BE \u09A8\u09C7\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC \u09A8\u09BE \u2014 \u0986\u0997\u09C7 \u09AC\u09BF\u09B2\u099F\u09BF \u099C\u09BE\u09B0\u09BF \u0995\u09B0\u09C1\u09A8\u0964", "invoice_draft");
    }
    const balance = Number(invoice.balance_amount);
    if (balance <= 0) {
      throw new HttpError(409, "\u098F\u0987 \u09AC\u09BF\u09B2\u09C7\u09B0 \u09B8\u09AC \u099F\u09BE\u0995\u09BE \u0987\u09A4\u09BF\u09AE\u09A7\u09CD\u09AF\u09C7 \u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09BF\u09A4\u0964", "already_settled");
    }
    if (paid > balance) {
      throw new HttpError(
        409,
        `\u09AC\u0995\u09C7\u09AF\u09BC\u09BE \u09F3${balance.toFixed(2)} \u2014 \u098F\u09B0 \u09AC\u09C7\u09B6\u09BF \u09A8\u09C7\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AC\u09C7 \u09A8\u09BE\u0964`,
        "over_payment",
        { field: "amount", balance }
      );
    }
    const applied = await c.query(
      `SELECT app.apply_payment_to_invoice(app.current_tenant(), $1, $2)::text AS status`,
      [invoiceId, paid]
    );
    const invoiceStatus = applied.rows[0].status;
    const receipt = await c.query(
      `INSERT INTO payment_receipts
         (tenant_id, receipt_no, invoice_id, student_id, amount, method, issued_by)
       VALUES (app.current_tenant(), app.next_receipt_no(), $1, $2, $3, $4::mfs_provider, $5)
       RETURNING id, receipt_no`,
      [invoiceId, invoice.student_id, paid, method, ctx.userId]
    );
    const issued = receipt.rows[0];
    const code = ACCOUNT_FOR[method] ?? "CASH";
    const accounts = await c.query(
      `SELECT code, id FROM ledger_accounts WHERE code IN ($1, 'FEE-INCOME')`,
      [code]
    );
    const bank = accounts.rows.find((r) => r.code === code)?.id;
    const income = accounts.rows.find((r) => r.code === "FEE-INCOME")?.id;
    let ledgerBatchId = null;
    if (bank && income) {
      const memo = `${METHOD_BN[method] ?? method} \u2014 ${invoice.invoice_no}` + (reference ? ` (${reference})` : "");
      const batch = await c.query(
        `INSERT INTO ledger_entries
           (tenant_id, batch_id, account_id, entry_date, debit, credit,
            reference_type, reference_id, memo)
         VALUES (app.current_tenant(), gen_random_uuid(), $1, app.today_dhaka(),
                 $2, 0, 'payment_receipt', $3, $4)
         RETURNING batch_id AS id`,
        [bank, paid, issued.id, memo]
      );
      ledgerBatchId = batch.rows[0].id;
      await c.query(
        `INSERT INTO ledger_entries
           (tenant_id, batch_id, account_id, entry_date, debit, credit,
            reference_type, reference_id, memo)
         VALUES (app.current_tenant(), $1, $2, app.today_dhaka(), 0, $3,
                 'payment_receipt', $4, $5)`,
        [ledgerBatchId, income, paid, issued.id, memo]
      );
    }
    await writeAudit(c, ctx, {
      action: "finance.payment.record",
      entityType: "payment_receipt",
      entityId: issued.id,
      after: {
        receiptNo: issued.receipt_no,
        invoiceNo: invoice.invoice_no,
        amount: paid,
        method,
        reference: reference || null,
        invoiceStatus,
        ledgerPosted: ledgerBatchId !== null
      }
    });
    return {
      ok: true,
      receiptId: issued.id,
      receiptNo: issued.receipt_no,
      amount: paid,
      method,
      methodBn: METHOD_BN[method] ?? method,
      invoiceStatus,
      // Honest about the books: a school whose chart was never seeded gets a
      // valid receipt and no ledger row, and the screen says so rather than
      // letting the accountant discover it at reconciliation.
      ledgerPosted: ledgerBatchId !== null
    };
  }, { write: true });
}

// packages/server-core/src/csv.ts
var CSV_BOM = "\uFEFF";
var FORMULA_LEAD = /^[=+\-@\t\r]/;
var PLAIN_NUMBER = /^[+-]?\d+(?:\.\d+)?$/;
function csvCell(value) {
  let v = value;
  if (FORMULA_LEAD.test(v) && !PLAIN_NUMBER.test(v)) v = `'${v}`;
  return /[",\r\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}
function csvLine(values) {
  return `${values.map(csvCell).join(",")}\r
`;
}

// packages/server-core/src/csv-response.ts
function beginCsvDownload(res, cors, o) {
  res.writeHead(200, {
    ...cors,
    "Content-Type": "text/csv; charset=utf-8",
    // `attachment` so the browser saves it instead of rendering a wall of
    // text, and a plain ASCII filename so no edge has to guess an encoding.
    "Content-Disposition": `attachment; filename="${o.filename}"`,
    // Belt and braces with the service worker's network-only rule: a proxy
    // between the school and us must not hold this either.
    "Cache-Control": "no-store, private, max-age=0",
    "Pragma": "no-cache",
    // The file is a download, never a document to be framed or sniffed.
    "X-Content-Type-Options": "nosniff"
  });
  res.write(CSV_BOM);
  res.write(csvLine(o.headers));
}
function writeCsvRow(res, values) {
  res.write(csvLine(values));
}
function csvFilename(dataset, on = /* @__PURE__ */ new Date()) {
  const d = on.toISOString().slice(0, 10);
  return `${dataset}-${d}.csv`;
}

// packages/server-core/src/export-dataset.ts
var cell = (v) => v === null || v === void 0 ? "" : String(v);
async function handleCsvExport(req, res, o) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireRole(claims, o.roles);
    const key = (query(req).get("dataset") ?? "").trim();
    const def = Object.prototype.hasOwnProperty.call(o.datasets, key) ? o.datasets[key] : void 0;
    if (!def) {
      throw new HttpError(
        400,
        `dataset must be one of: ${Object.keys(o.datasets).join(", ")}`,
        "unknown_dataset"
      );
    }
    const db = await sharedDb();
    const actor = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    await db.withTenant(actor, async (client) => {
      const rows = await def.select(client);
      beginCsvDownload(res, cors, {
        filename: csvFilename(key),
        headers: def.headers
      });
      for (const r of rows) writeCsvRow(res, def.row(r));
      await writeAudit(client, actor, {
        action: "ops.data.export",
        entityType: "export",
        after: { dataset: key, rows: rows.length }
      });
    });
    res.end();
  } catch (err) {
    if (res.headersSent) {
      res.end();
      return;
    }
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code, message: err.message }, cors);
      return;
    }
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/finance-svc/api/export.ts
var EXPORT_ROLES = ["principal", "school_owner", "it_admin", "accountant"];
var INVOICE_BN = {
  draft: "\u0996\u09B8\u09A1\u09BC\u09BE",
  issued: "\u0987\u09B8\u09CD\u09AF\u09C1 \u0995\u09B0\u09BE",
  partly_paid: "\u0986\u0982\u09B6\u09BF\u0995 \u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09BF\u09A4",
  paid: "\u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09BF\u09A4",
  overdue: "\u09AC\u0995\u09C7\u09AF\u09BC\u09BE",
  waived: "\u09AE\u0993\u0995\u09C1\u09AB",
  cancelled: "\u09AC\u09BE\u09A4\u09BF\u09B2"
};
var METHOD_BN2 = {
  cash: "\u09A8\u0997\u09A6",
  bkash: "\u09AC\u09BF\u0995\u09BE\u09B6",
  nagad: "\u09A8\u0997\u09A6 (Nagad)",
  rocket: "\u09B0\u0995\u09C7\u099F",
  bank: "\u09AC\u09CD\u09AF\u09BE\u0982\u0995",
  cheque: "\u099A\u09C7\u0995",
  card: "\u0995\u09BE\u09B0\u09CD\u09A1",
  other: "\u0985\u09A8\u09CD\u09AF\u09BE\u09A8\u09CD\u09AF"
};
var bnOf = (map, v) => v ? map[v] ?? v : "";
var fees = {
  headers: [
    "\u0987\u09A8\u09AD\u09AF\u09BC\u09C7\u09B8 \u09A8\u09AE\u09CD\u09AC\u09B0",
    "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09B0\u09CD\u09A5\u09C0 \u0986\u0987\u09A1\u09BF",
    "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09B0\u09CD\u09A5\u09C0\u09B0 \u09A8\u09BE\u09AE",
    "\u09B6\u09CD\u09B0\u09C7\u09A3\u09BF",
    "\u09B6\u09BE\u0996\u09BE",
    "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09AC\u09B0\u09CD\u09B7",
    "\u09AC\u09BF\u09B2\u09BF\u0982 \u09B8\u09AE\u09AF\u09BC\u0995\u09BE\u09B2",
    "\u0987\u09B8\u09CD\u09AF\u09C1\u09B0 \u09A4\u09BE\u09B0\u09BF\u0996",
    "\u09B6\u09C7\u09B7 \u09A4\u09BE\u09B0\u09BF\u0996",
    "\u0989\u09AA\u09AE\u09CB\u099F",
    "\u09AE\u0993\u0995\u09C1\u09AB",
    "\u09AC\u09BF\u09B2\u09AE\u09CD\u09AC \u09AB\u09BF",
    "\u09AE\u09CB\u099F",
    "\u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09BF\u09A4",
    "\u09AC\u0995\u09C7\u09AF\u09BC\u09BE",
    "\u09AE\u09C1\u09A6\u09CD\u09B0\u09BE",
    "\u0985\u09AC\u09B8\u09CD\u09A5\u09BE",
    "\u09AB\u09BF \u0996\u09BE\u09A4",
    "\u09B0\u09B8\u09BF\u09A6 \u09A8\u09AE\u09CD\u09AC\u09B0",
    "\u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09C7\u09B0 \u09AE\u09BE\u09A7\u09CD\u09AF\u09AE",
    "\u09B8\u09B0\u09CD\u09AC\u09B6\u09C7\u09B7 \u09AA\u09B0\u09BF\u09B6\u09CB\u09A7",
    "\u09AE\u09A8\u09CD\u09A4\u09AC\u09CD\u09AF"
  ],
  /**
   * Every invoice, with what it was for and what has been paid against it.
   *
   * The fee HEADS and the RECEIPTS are aggregated into their own cells
   * rather than joined. A three-line invoice paid in two instalments is
   * still ONE bill; joining either would emit six rows for it and make the
   * "মোট" column sum to six times the school's actual billing — a number a
   * head teacher would act on.
   *
   * Cancelled and waived invoices are included, with their status named.
   * They are part of the school's billing history and an export that showed
   * only live bills would not reconcile against their own ledger.
   */
  async select(client) {
    const { rows } = await client.query(
      `SELECT i.invoice_no,
              sp.student_code,
              u.full_name_bn      AS student_name,
              c.name_bn           AS class_name,
              s.name              AS section_name,
              ay.label            AS year_label,
              i.billing_period,
              i.issued_on::text   AS issued_on,
              i.due_on::text      AS due_on,
              i.subtotal::text, i.waiver_total::text, i.late_fee::text,
              i.total_amount::text, i.paid_amount::text, i.balance_amount::text,
              i.currency, i.status::text AS status,
              (SELECT string_agg(COALESCE(fh.name_bn, il.description_bn)
                                 || ' (' || il.net_amount::text || ')', '; '
                                 ORDER BY fh.name_bn)
                 FROM invoice_lines il
                 LEFT JOIN fee_heads fh ON fh.id = il.fee_head_id
                WHERE il.invoice_id = i.id) AS heads,
              (SELECT string_agg(pr.receipt_no, '; ' ORDER BY pr.issued_at)
                 FROM payment_receipts pr WHERE pr.invoice_id = i.id) AS receipts,
              (SELECT string_agg(DISTINCT pr.method::text, '; ')
                 FROM payment_receipts pr WHERE pr.invoice_id = i.id) AS methods,
              (SELECT max(pr.issued_at)::text
                 FROM payment_receipts pr WHERE pr.invoice_id = i.id) AS last_paid_at,
              i.notes
         FROM invoices i
         JOIN users u ON u.id = i.student_id AND u.deleted_at IS NULL
         LEFT JOIN student_profiles sp ON sp.user_id = i.student_id
         LEFT JOIN sections s ON s.id = i.section_id
         LEFT JOIN classes  c ON c.id = s.class_id
         LEFT JOIN academic_years ay ON ay.id = i.academic_year_id
        ORDER BY i.issued_on DESC, i.invoice_no`
    );
    return rows;
  },
  row: (r) => [
    cell(r.invoice_no),
    cell(r.student_code),
    cell(r.student_name),
    cell(r.class_name),
    cell(r.section_name),
    cell(r.year_label),
    cell(r.billing_period),
    cell(r.issued_on),
    cell(r.due_on),
    // Plain decimals — see the file header. A spreadsheet must be able to
    // add these.
    cell(r.subtotal),
    cell(r.waiver_total),
    cell(r.late_fee),
    cell(r.total_amount),
    cell(r.paid_amount),
    cell(r.balance_amount),
    cell(r.currency ?? "BDT"),
    bnOf(INVOICE_BN, r.status),
    cell(r.heads),
    cell(r.receipts),
    (r.methods ?? "").split("; ").filter(Boolean).map((m) => bnOf(METHOD_BN2, m)).join("; "),
    cell(r.last_paid_at),
    cell(r.notes)
  ]
};
async function handler3(req, res) {
  return handleCsvExport(req, res, {
    roles: EXPORT_ROLES,
    datasets: { fees }
  });
}

// services/finance-svc/api/index.ts
var SERVICE3 = "finance";
var UUID_RE3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function invoices(req, res, cors) {
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const claims = await authenticate(req);
  const studentId = query(req).get("studentId") ?? "";
  if (studentId && !UUID_RE3.test(studentId)) {
    throw new HttpError(400, "studentId must be a valid uuid", "invalid_student_id");
  }
  const db = await sharedDb();
  const rows = await db.withTenant(
    { tenantId: claims.tid, userId: claims.sub, role: claims.role, service: SERVICE3 },
    async (client) => {
      const r = await client.query(
        `SELECT i.id, i.invoice_no, i.student_id, i.billing_period, i.issued_on, i.due_on,
                i.subtotal, i.waiver_total, i.late_fee, i.total_amount, i.paid_amount,
                i.balance_amount, i.status, i.currency,
                COALESCE(
                  (SELECT jsonb_agg(jsonb_build_object(
                     'descriptionBn', l.description_bn,
                     'amount', l.amount::text,
                     'waiverAmount', l.waiver_amount::text,
                     'netAmount', l.net_amount::text))
                     FROM invoice_lines l WHERE l.invoice_id = i.id),
                  '[]'::jsonb) AS lines
           FROM invoices i
          WHERE ($1::uuid IS NULL OR i.student_id = $1)
            AND i.status <> 'draft'
          ORDER BY i.issued_on DESC, i.invoice_no DESC
          LIMIT 100`,
        [studentId || null]
      );
      return r.rows;
    }
  );
  json(res, 200, {
    invoices: rows.map((r) => ({
      id: r.id,
      invoiceNo: r.invoice_no,
      studentId: r.student_id,
      billingPeriod: r.billing_period,
      issuedOn: r.issued_on,
      dueOn: r.due_on,
      // Money as decimal strings, per docs/03 conventions — never floats.
      subtotal: r.subtotal,
      waiverTotal: r.waiver_total,
      lateFee: r.late_fee,
      totalAmount: r.total_amount,
      paidAmount: r.paid_amount,
      balanceAmount: r.balance_amount,
      status: r.status,
      currency: r.currency,
      lines: r.lines
    }))
  }, cors);
}
var PAY_PROVIDERS = /* @__PURE__ */ new Set(["bkash", "nagad", "rocket"]);
async function pay(req, res, cors) {
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const claims = await authenticate(req);
  const body = await readJson(req);
  const invoiceId = body.invoiceId ?? "";
  const provider = body.provider ?? "";
  if (!UUID_RE3.test(invoiceId)) throw new HttpError(400, "invoiceId must be a valid uuid", "invalid_invoice_id");
  if (!PAY_PROVIDERS.has(provider)) {
    throw new HttpError(400, `provider must be one of ${[...PAY_PROVIDERS].join(", ")}`, "invalid_provider");
  }
  if (!mfsPaymentsEnabled()) {
    json(res, 503, {
      error: "mfs_disabled",
      message: "online fee payment is not yet available \u2014 pay at the school office"
    }, cors);
    return;
  }
  json(res, 501, { error: "not_implemented" }, cors);
}
async function receipts(req, res, cors) {
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const claims = await authenticate(req);
  const invoiceId = query(req).get("invoiceId") ?? "";
  if (!UUID_RE3.test(invoiceId)) throw new HttpError(400, "invoiceId must be a valid uuid", "invalid_invoice_id");
  const db = await sharedDb();
  const rows = await db.withTenant(
    { tenantId: claims.tid, userId: claims.sub, role: claims.role, service: SERVICE3 },
    async (client) => {
      const r = await client.query(
        `SELECT pr.id, pr.receipt_no, pr.amount, pr.method, pr.issued_at,
                mt.gateway_trx_id, pr.pdf_object_key
           FROM payment_receipts pr
           LEFT JOIN mfs_transactions mt ON mt.id = pr.mfs_transaction_id
          WHERE pr.invoice_id = $1
          ORDER BY pr.issued_at DESC`,
        [invoiceId]
      );
      return r.rows;
    }
  );
  json(res, 200, {
    receipts: rows.map((r) => ({
      id: r.id,
      receiptNo: r.receipt_no,
      amount: r.amount,
      method: r.method,
      issuedAt: r.issued_at,
      gatewayTrxId: r.gateway_trx_id,
      pdfObjectKey: r.pdf_object_key
    }))
  }, cors);
}
var PERIOD_RE = /^\d{4}-(0[1-9]|1[0-2])$/;
var BILLING_ROLES = ["principal", "school_owner", "accountant"];
async function generate(req, res, cors) {
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const claims = await authenticate(req);
  requireRole(claims, BILLING_ROLES);
  const body = await readJson(req);
  const period = body.billingPeriod ?? "";
  if (!PERIOD_RE.test(period)) {
    throw new HttpError(400, "billingPeriod must be YYYY-MM", "invalid_billing_period");
  }
  const periodStart = `${period}-01`;
  const db = await sharedDb();
  const result = await db.withTenant(
    { tenantId: claims.tid, userId: claims.sub, role: claims.role, service: SERVICE3 },
    async (client) => {
      const yearRes = await client.query(
        `SELECT id FROM academic_years
          WHERE $1::date BETWEEN starts_on AND ends_on
          ORDER BY starts_on DESC LIMIT 1`,
        [periodStart]
      );
      const yearId = yearRes.rows[0]?.id;
      if (!yearId) throw new HttpError(422, "no academic year covers that billing period", "no_academic_year");
      const lines = await client.query(
        `WITH eligible AS (
           SELECT en.student_id, en.section_id, s.class_id
             FROM enrolments en
             JOIN sections s ON s.id = en.section_id
            WHERE en.academic_year_id = $1
              AND en.status = 'active'
              AND NOT EXISTS (SELECT 1 FROM invoices i
                               WHERE i.student_id = en.student_id
                                 AND i.billing_period = $2)
         ),
         fee_lines AS (
           -- class-specific structure wins over the class-wide (NULL) one
           SELECT DISTINCT ON (e.student_id, fs.fee_head_id)
                  e.student_id, e.section_id, fs.fee_head_id, fh.name_bn,
                  fs.amount, fs.due_day_of_month
             FROM eligible e
             JOIN fee_structures fs
               ON fs.academic_year_id = $1
              AND (fs.class_id = e.class_id OR fs.class_id IS NULL)
              AND fs.quota_category IS NULL
             JOIN fee_heads fh
               ON fh.id = fs.fee_head_id AND fh.is_active AND fh.frequency = 'monthly'
            ORDER BY e.student_id, fs.fee_head_id, fs.class_id NULLS LAST
         ),
         waived AS (
           SELECT fl.*, LEAST(fl.amount, COALESCE(w.best, 0)) AS waiver_amount
             FROM fee_lines fl
             LEFT JOIN LATERAL (
               SELECT MAX(LEAST(fl.amount,
                                COALESCE(fw.flat_off, 0)
                                + fl.amount * COALESCE(fw.percent_off, 0) / 100)) AS best
                 FROM fee_waivers fw
                WHERE fw.student_id = fl.student_id
                  AND fw.academic_year_id = $1
                  AND (fw.fee_head_id = fl.fee_head_id OR fw.fee_head_id IS NULL)
                  AND fw.valid_from <= $3::date
                  AND (fw.valid_to IS NULL OR fw.valid_to >= $3::date)
             ) w ON true
         ),
         agg AS (
           SELECT student_id,
                  MIN(section_id::text)::uuid AS section_id,
                  SUM(amount) AS subtotal,
                  SUM(waiver_amount) AS waiver_total,
                  MIN(COALESCE(due_day_of_month, 10)) AS due_day
             FROM waived
            GROUP BY student_id
         ),
         numbered AS (
           SELECT a.*,
                  row_number() OVER (ORDER BY a.student_id) AS rn,
                  (SELECT count(*) FROM invoices i WHERE i.billing_period = $2) AS base
             FROM agg a
         ),
         new_inv AS (
           INSERT INTO invoices
             (tenant_id, invoice_no, student_id, academic_year_id, section_id,
              billing_period, issued_on, due_on, subtotal, waiver_total,
              total_amount, status)
           SELECT app.current_tenant(),
                  'INV-' || $2 || '-' || lpad((n.base + n.rn)::text, 5, '0'),
                  n.student_id, $1, n.section_id, $2,
                  app.today_dhaka(),
                  $3::date + (n.due_day - 1),
                  n.subtotal, n.waiver_total, n.subtotal - n.waiver_total, 'issued'
             FROM numbered n
           RETURNING id, student_id
         )
         INSERT INTO invoice_lines
           (tenant_id, invoice_id, fee_head_id, description_bn, amount, waiver_amount)
         SELECT app.current_tenant(), ni.id, w.fee_head_id, w.name_bn, w.amount, w.waiver_amount
           FROM waived w
           JOIN new_inv ni ON ni.student_id = w.student_id
         RETURNING invoice_id`,
        [yearId, period, periodStart]
      );
      const invoiceCount = new Set(lines.rows.map((r) => r.invoice_id)).size;
      let notified = 0;
      if (invoiceCount > 0) {
        const emitted = await client.query(
          `SELECT recipients FROM app.emit_auto_notice(
             'invoice', md5('invoice:' || $1::text)::uuid, $2, $3,
             'fee'::notice_category, '{"type":"guardians_payers"}'::jsonb, false)`,
          [
            period,
            `${period} \u09AE\u09BE\u09B8\u09C7\u09B0 \u09AC\u09C7\u09A4\u09A8 \u0993 \u09AB\u09BF \u09AA\u09CD\u09B0\u09B8\u09CD\u09A4\u09C1\u09A4`,
            "\u0985\u09CD\u09AF\u09BE\u09AA\u09C7\u09B0 \u09AC\u09C7\u09A4\u09A8 \u0993 \u09AB\u09BF \u0985\u0982\u09B6\u09C7 \u0987\u09A8\u09AD\u09AF\u09BC\u09C7\u09B8 \u0993 \u09AA\u09B0\u09BF\u09B6\u09CB\u09A7\u09C7\u09B0 \u09B6\u09C7\u09B7 \u09A4\u09BE\u09B0\u09BF\u0996 \u09A6\u09C7\u0996\u09BE \u09AF\u09BE\u09AC\u09C7\u0964"
          ]
        );
        notified = emitted.rows[0]?.recipients ?? 0;
      }
      return { invoicesCreated: invoiceCount, linesCreated: lines.rowCount ?? 0, notified };
    }
  );
  json(res, 200, { ok: true, billingPeriod: period, ...result }, cors);
}
var LEDGER_ROLES = ["principal", "school_owner", "accountant"];
async function ledger(req, res, cors) {
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const claims = await authenticate(req);
  requireRole(claims, LEDGER_ROLES);
  const db = await sharedDb();
  const payload = await db.withTenant(
    { tenantId: claims.tid, userId: claims.sub, role: claims.role, service: SERVICE3 },
    async (client) => {
      const accountsRes = await client.query(
        `SELECT a.code, a.name_bn, a.type,
                CASE WHEN a.type IN ('income','liability','equity')
                     THEN COALESCE(SUM(e.credit - e.debit), 0)
                     ELSE COALESCE(SUM(e.debit - e.credit), 0)
                END::text AS balance
           FROM ledger_accounts a
           LEFT JOIN ledger_entries e ON e.account_id = a.id
          GROUP BY a.id, a.code, a.name_bn, a.type
          ORDER BY a.type, a.code`
      );
      const batchesRes = await client.query(
        `WITH recent AS (
           SELECT DISTINCT batch_id, MAX(created_at) AS created_at
             FROM ledger_entries
            GROUP BY batch_id
            ORDER BY MAX(created_at) DESC
            LIMIT 50
         )
         SELECT e.batch_id::text,
                e.entry_date::text,
                COALESCE(e.memo, '') AS memo,
                a.code AS account_code,
                e.debit::text,
                e.credit::text
           FROM ledger_entries e
           JOIN recent r ON r.batch_id = e.batch_id
           JOIN ledger_accounts a ON a.id = e.account_id
          ORDER BY r.created_at DESC, e.created_at`
      );
      const reconRes = await client.query(
        `SELECT provider::text,
                COALESCE(SUM(amount), 0)::text AS posted,
                COALESCE(SUM(amount) FILTER (WHERE reconciled_at IS NOT NULL), 0)::text AS reconciled
           FROM mfs_transactions
          WHERE status = 'completed'
          GROUP BY provider
          ORDER BY provider`
      );
      const byBatch = /* @__PURE__ */ new Map();
      for (const row of batchesRes.rows) {
        let b = byBatch.get(row.batch_id);
        if (!b) {
          b = { batchId: row.batch_id, entryDate: row.entry_date, memo: row.memo, lines: [] };
          byBatch.set(row.batch_id, b);
        }
        b.lines.push({ accountCode: row.account_code, debit: row.debit, credit: row.credit });
      }
      const PROVIDER_LABEL = {
        bkash: "bKash",
        nagad: "Nagad",
        rocket: "Rocket",
        upay: "Upay",
        bank_transfer: "Bank",
        cash: "Cash",
        cheque: "Cheque"
      };
      return {
        accounts: accountsRes.rows.map((a) => ({
          code: a.code,
          nameBn: a.name_bn,
          type: a.type,
          balance: a.balance
        })),
        batches: [...byBatch.values()],
        reconciliation: reconRes.rows.map((r) => ({
          provider: PROVIDER_LABEL[r.provider] ?? r.provider,
          posted: r.posted,
          reconciled: r.reconciled
        }))
      };
    }
  );
  json(res, 200, payload, cors);
}
var ROUTES = {
  export: handler3,
  invoices,
  pay,
  receipts,
  generate,
  ledger,
  feestructures: handler,
  payments: handler2
};
async function handler4(req, res) {
  const cors = corsHeaders([], "GET, POST, PATCH, DELETE, OPTIONS");
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  const path = new URL(req.url ?? "/", "http://internal").pathname;
  const sub = path.split("/").filter(Boolean).pop() ?? "";
  const route = ROUTES[sub];
  if (!route) {
    json(res, 404, { error: "not_found" }, cors);
    return;
  }
  {
    const cls = req.method === "GET" ? "read" : "mutation";
    if (!await enforceRateLimit(req, res, cors, cls)) return;
  }
  try {
    await route(req, res, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(
        res,
        err.status,
        { error: err.code ?? "error", message: err.message, ...err.detail ?? {} },
        cors
      );
      return;
    }
    const e = err;
    if (e.code === "23505" && ((e.constraint ?? "").startsWith("fee_structures_tenant_id") || e.constraint === "uq_fee_structure_scope")) {
      json(res, 409, {
        error: "duplicate_structure",
        message: "\u098F\u0987 \u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09AC\u09B0\u09CD\u09B7\u09C7 \u098F\u0987 \u09B6\u09CD\u09B0\u09C7\u09A3\u09BF\u09B0 \u099C\u09A8\u09CD\u09AF \u098F\u0987 \u09AB\u09BF \u0987\u09A4\u09BF\u09AE\u09A7\u09CD\u09AF\u09C7 \u09A8\u09BF\u09B0\u09CD\u09A7\u09BE\u09B0\u09BF\u09A4 \u0986\u099B\u09C7\u0964",
        field: "feeHeadId"
      }, cors);
      return;
    }
    console.error(`[finance/${sub}] unexpected error`, err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}
export {
  handler4 as default
};
